-- ============================================================
--  FINTECH — DDL Oracle (19c+) — RM570791
--  Estrutura espelhada das tabelas atuais do projeto (scripts/fintechapp_schema.sql),
--  com nomes no padrão T_FIN_<ENTIDADE> e tipos convertidos para Oracle.
--
--  Convenções:
--    - PK própria:   <entidade>_id   NUMBER GENERATED BY DEFAULT AS IDENTITY
--    - Código único: <entidade>_code VARCHAR2(6) NOT NULL UNIQUE
--    - FKs compostas pelo par (xxx_id, xxx_code); o par é UNIQUE na tabela-pai.
--    - Campos lógicos (BOOLEAN no PostgreSQL) viram CHAR(1) com 'S'/'N'.
--    - TEXT vira VARCHAR2(4000).
--  Diagrama: modelo_relacional_eraser.png
-- ============================================================


-- ─────────────────────────────────────────────
--  CADASTROS BASE
-- ─────────────────────────────────────────────
CREATE TABLE t_fin_usuarios (
    usuario_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    usuario_code      VARCHAR2(6)   NOT NULL,
    cpf               VARCHAR2(255) NOT NULL,
    nome              VARCHAR2(255) NOT NULL,
    email             VARCHAR2(255) NOT NULL,
    senha             VARCHAR2(255) NOT NULL,
    telefone          VARCHAR2(255),
    telegram_chatid   NUMBER,
    whatsapp_chatid   NUMBER,
    email_verificado  CHAR(1)       DEFAULT 'N',
    dt_nascimento     DATE          NOT NULL,
    CONSTRAINT pk_t_fin_usuarios PRIMARY KEY (usuario_id),
    CONSTRAINT uk_t_fin_usuarios_code    UNIQUE (usuario_code),
    CONSTRAINT uk_t_fin_usuarios_id_code UNIQUE (usuario_id, usuario_code),
    CONSTRAINT uk_t_fin_usuarios_cpf     UNIQUE (cpf),
    CONSTRAINT uk_t_fin_usuarios_email   UNIQUE (email),
    CONSTRAINT ck_t_fin_usuarios_email_verif CHECK (email_verificado IN ('S','N'))
);

CREATE TABLE t_fin_bancos (
    banco_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    banco_code  VARCHAR2(6)   NOT NULL,
    nome        VARCHAR2(100) NOT NULL,
    descricao   VARCHAR2(255),
    cor_hex     VARCHAR2(7),
    icone       VARCHAR2(50),
    CONSTRAINT pk_t_fin_bancos PRIMARY KEY (banco_id),
    CONSTRAINT uk_t_fin_bancos_code    UNIQUE (banco_code),
    CONSTRAINT uk_t_fin_bancos_id_code UNIQUE (banco_id, banco_code)
);

CREATE TABLE t_fin_categorias (
    categoria_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    categoria_code  VARCHAR2(6)   NOT NULL,
    nome            VARCHAR2(100) NOT NULL,
    tipo            VARCHAR2(10)  NOT NULL,
    icone           VARCHAR2(50),
    cor_hex         VARCHAR2(7),
    padrao          CHAR(1)       DEFAULT 'N',
    criado_em       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_t_fin_categorias PRIMARY KEY (categoria_id),
    CONSTRAINT uk_t_fin_categorias_code    UNIQUE (categoria_code),
    CONSTRAINT uk_t_fin_categorias_id_code UNIQUE (categoria_id, categoria_code),
    CONSTRAINT ck_t_fin_categorias_tipo   CHECK (tipo IN ('RECEITA','GASTO','AMBOS')),
    CONSTRAINT ck_t_fin_categorias_padrao CHECK (padrao IN ('S','N'))
);

CREATE TABLE t_fin_categoria_thresholds (
    categoria_threshold_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    categoria_threshold_code  VARCHAR2(6) NOT NULL,
    categoria_id              NUMBER      NOT NULL,
    categoria_code            VARCHAR2(6) NOT NULL,
    threshold_auto            NUMBER(3)   DEFAULT 70 NOT NULL,
    threshold_alerta          NUMBER(3)   DEFAULT 50 NOT NULL,
    ambiguidade_alta          CHAR(1)     DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_t_fin_categoria_thresholds PRIMARY KEY (categoria_threshold_id),
    CONSTRAINT uk_t_fin_cat_thresholds_code UNIQUE (categoria_threshold_code),
    CONSTRAINT uk_t_fin_cat_thresholds_cat  UNIQUE (categoria_id),
    CONSTRAINT fk_t_fin_cat_thresholds_cat FOREIGN KEY (categoria_id, categoria_code)
        REFERENCES t_fin_categorias (categoria_id, categoria_code),
    CONSTRAINT ck_t_fin_cat_thresholds_amb CHECK (ambiguidade_alta IN ('S','N'))
);

CREATE TABLE t_fin_motivos_cancelamento (
    motivo_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    motivo_code       VARCHAR2(6)   NOT NULL,
    descricao         VARCHAR2(255) NOT NULL,
    origem_permitida  VARCHAR2(20)  DEFAULT 'todos' NOT NULL,
    ativo             CHAR(1)       DEFAULT 'S' NOT NULL,
    criado_em         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_t_fin_motivos_cancelamento PRIMARY KEY (motivo_id),
    CONSTRAINT uk_t_fin_motivos_code    UNIQUE (motivo_code),
    CONSTRAINT uk_t_fin_motivos_id_code UNIQUE (motivo_id, motivo_code),
    CONSTRAINT ck_t_fin_motivos_origem CHECK (origem_permitida IN ('usuario','sistema','admin','todos')),
    CONSTRAINT ck_t_fin_motivos_ativo  CHECK (ativo IN ('S','N'))
);

CREATE TABLE t_fin_parser_versoes (
    parser_versao_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    parser_versao_code  VARCHAR2(6)   NOT NULL,
    banco               VARCHAR2(100) NOT NULL,
    versao              VARCHAR2(20)  NOT NULL,
    ativo               CHAR(1)       DEFAULT 'S' NOT NULL,
    score_qualidade     NUMBER(4,3),
    total_usos          NUMBER(10)    DEFAULT 0 NOT NULL,
    total_erros         NUMBER(10)    DEFAULT 0 NOT NULL,
    descricao           VARCHAR2(4000),
    depreciado_em       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_t_fin_parser_versoes PRIMARY KEY (parser_versao_id),
    CONSTRAINT uk_t_fin_parser_code    UNIQUE (parser_versao_code),
    CONSTRAINT uk_t_fin_parser_id_code UNIQUE (parser_versao_id, parser_versao_code),
    CONSTRAINT ck_t_fin_parser_ativo CHECK (ativo IN ('S','N'))
);


-- ─────────────────────────────────────────────
--  CONTAS E MOVIMENTAÇÕES
-- ─────────────────────────────────────────────
CREATE TABLE t_fin_contas_financeiras (
    conta_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    conta_code       VARCHAR2(6)   NOT NULL,
    usuario_id       NUMBER        NOT NULL,
    usuario_code     VARCHAR2(6)   NOT NULL,
    banco_id         NUMBER        NOT NULL,
    banco_code       VARCHAR2(6)   NOT NULL,
    tipo             VARCHAR2(20)  NOT NULL,
    saldo_inicial    NUMBER(15,2)  DEFAULT 0 NOT NULL,
    saldo_atual      NUMBER(15,2)  DEFAULT 0 NOT NULL,
    saldo_economias  NUMBER(15,2)  DEFAULT 0 NOT NULL,
    padrao           CHAR(1)       DEFAULT 'N',
    ativa            CHAR(1)       DEFAULT 'S',
    criado_em        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    atualizado_em    TIMESTAMP WITH TIME ZONE,
    ind_delete       VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    deleted_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_t_fin_contas_financeiras PRIMARY KEY (conta_id),
    CONSTRAINT uk_t_fin_contas_code    UNIQUE (conta_code),
    CONSTRAINT uk_t_fin_contas_id_code UNIQUE (conta_id, conta_code),
    CONSTRAINT fk_t_fin_contas_usuario FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES t_fin_usuarios (usuario_id, usuario_code),
    CONSTRAINT fk_t_fin_contas_banco FOREIGN KEY (banco_id, banco_code)
        REFERENCES t_fin_bancos (banco_id, banco_code),
    CONSTRAINT ck_t_fin_contas_tipo CHECK (tipo IN ('corrente','poupanca','cartao','dinheiro','investimento')),
    CONSTRAINT ck_t_fin_contas_padrao CHECK (padrao IN ('S','N')),
    CONSTRAINT ck_t_fin_contas_ativa  CHECK (ativa IN ('S','N')),
    CONSTRAINT ck_t_fin_contas_ind_delete CHECK (ind_delete IN ('S','N'))
);

-- Receitas e despesas: a direção vem do tipo da categoria
-- (RECEITA / GASTO); em categorias AMBOS, valor negativo = despesa.
CREATE TABLE t_fin_transacoes (
    transacoes_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    transacoes_code         VARCHAR2(6)   NOT NULL,
    conta_id                NUMBER        NOT NULL,
    conta_code              VARCHAR2(6)   NOT NULL,
    ind_estorno             VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    descricao               VARCHAR2(4000),
    valor                   NUMBER(15,2)  NOT NULL,
    data_transacao          DATE          NOT NULL,
    categoria_id            NUMBER        NOT NULL,
    categoria_code          VARCHAR2(6)   NOT NULL,
    estabelecimento         VARCHAR2(255),
    origem                  VARCHAR2(20)  DEFAULT 'manual' NOT NULL,
    status_revisao          VARCHAR2(30)  DEFAULT 'EXTRAIDA' NOT NULL,
    confianca_ia            NUMBER(3),
    recorrente              CHAR(1)       DEFAULT 'N',
    periodo_recorrencia     DATE,
    observacao              VARCHAR2(4000),
    deleted_at              TIMESTAMP WITH TIME ZONE,
    estornado_at            TIMESTAMP WITH TIME ZONE,
    versao                  NUMBER(10)    DEFAULT 1 NOT NULL,
    criado_em               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    atualizado_em           TIMESTAMP WITH TIME ZONE,
    transacao_estornada_id  NUMBER,
    saldo_aplicado          CHAR(1)       DEFAULT 'S',
    CONSTRAINT pk_t_fin_transacoes PRIMARY KEY (transacoes_id),
    CONSTRAINT uk_t_fin_transacoes_code    UNIQUE (transacoes_code),
    CONSTRAINT uk_t_fin_transacoes_id_code UNIQUE (transacoes_id, transacoes_code),
    CONSTRAINT fk_t_fin_transacoes_conta FOREIGN KEY (conta_id, conta_code)
        REFERENCES t_fin_contas_financeiras (conta_id, conta_code),
    CONSTRAINT fk_t_fin_transacoes_categoria FOREIGN KEY (categoria_id, categoria_code)
        REFERENCES t_fin_categorias (categoria_id, categoria_code),
    CONSTRAINT fk_t_fin_transacoes_estornada FOREIGN KEY (transacao_estornada_id)
        REFERENCES t_fin_transacoes (transacoes_id),
    CONSTRAINT ck_t_fin_transacoes_origem CHECK (origem IN ('manual','pdf','api','importado')),
    CONSTRAINT ck_t_fin_transacoes_status CHECK (status_revisao IN (
        'EXTRAIDA','CLASSIFICADA','PENDENTE_REVISAO','CONFIRMADA','IGNORADA','ARQUIVADA')),
    CONSTRAINT ck_t_fin_transacoes_estorno CHECK (ind_estorno IN ('S','N')),
    CONSTRAINT ck_t_fin_transacoes_recorr  CHECK (recorrente IN ('S','N')),
    CONSTRAINT ck_t_fin_transacoes_saldo   CHECK (saldo_aplicado IN ('S','N')),
    CONSTRAINT ck_t_fin_transacoes_valor   CHECK (valor <> 0)
);

CREATE TABLE t_fin_transacoes_canceladas (
    transacao_cancelada_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    transacao_cancelada_code  VARCHAR2(6)  NOT NULL,
    transacao_id              NUMBER       NOT NULL,
    transacao_code            VARCHAR2(6)  NOT NULL,
    motivo_id                 NUMBER       NOT NULL,
    motivo_code               VARCHAR2(6)  NOT NULL,
    cancelado_por             VARCHAR2(20) DEFAULT 'usuario' NOT NULL,
    valor_original            NUMBER(15,2) NOT NULL,
    observacao                VARCHAR2(4000),
    ip_origem                 VARCHAR2(45),
    cancelado_em              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_t_fin_transacoes_canceladas PRIMARY KEY (transacao_cancelada_id),
    CONSTRAINT uk_t_fin_trans_canc_code UNIQUE (transacao_cancelada_code),
    CONSTRAINT fk_t_fin_trans_canc_transacao FOREIGN KEY (transacao_id, transacao_code)
        REFERENCES t_fin_transacoes (transacoes_id, transacoes_code),
    CONSTRAINT fk_t_fin_trans_canc_motivo FOREIGN KEY (motivo_id, motivo_code)
        REFERENCES t_fin_motivos_cancelamento (motivo_id, motivo_code),
    CONSTRAINT ck_t_fin_trans_canc_por CHECK (cancelado_por IN ('usuario','sistema','admin'))
);

CREATE TABLE t_fin_movimentacoes_economia (
    movimentacao_economia_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    movimentacao_economia_code  VARCHAR2(6)  NOT NULL,
    conta_id                    NUMBER       NOT NULL,
    conta_code                  VARCHAR2(6)  NOT NULL,
    tipo                        VARCHAR2(10) NOT NULL,
    valor                       NUMBER(15,2) NOT NULL,
    descricao                   VARCHAR2(4000),
    data_movimentacao           TIMESTAMP WITH TIME ZONE NOT NULL,
    criado_em                   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_t_fin_movimentacoes_economia PRIMARY KEY (movimentacao_economia_id),
    CONSTRAINT uk_t_fin_mov_economia_code UNIQUE (movimentacao_economia_code),
    CONSTRAINT fk_t_fin_mov_economia_conta FOREIGN KEY (conta_id, conta_code)
        REFERENCES t_fin_contas_financeiras (conta_id, conta_code),
    CONSTRAINT ck_t_fin_mov_economia_tipo CHECK (tipo IN ('APORTE','RESGATE'))
);

-- Tabela nova: investimentos do usuário, vinculados à conta de onde saiu o dinheiro.
CREATE TABLE t_fin_investimentos (
    investimento_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    investimento_code  VARCHAR2(6)   NOT NULL,
    usuario_id         NUMBER        NOT NULL,
    usuario_code       VARCHAR2(6)   NOT NULL,
    conta_id           NUMBER        NOT NULL,
    conta_code         VARCHAR2(6)   NOT NULL,
    nome               VARCHAR2(100) NOT NULL,
    tipo               VARCHAR2(20)  NOT NULL,
    valor_aplicado     NUMBER(15,2)  NOT NULL,
    rentabilidade_aa   NUMBER(7,4),
    data_aplicacao     DATE          NOT NULL,
    data_vencimento    DATE,
    status             VARCHAR2(10)  DEFAULT 'ATIVO' NOT NULL,
    criado_em          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    atualizado_em      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_t_fin_investimentos PRIMARY KEY (investimento_id),
    CONSTRAINT uk_t_fin_investimentos_code UNIQUE (investimento_code),
    CONSTRAINT fk_t_fin_invest_usuario FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES t_fin_usuarios (usuario_id, usuario_code),
    CONSTRAINT fk_t_fin_invest_conta FOREIGN KEY (conta_id, conta_code)
        REFERENCES t_fin_contas_financeiras (conta_id, conta_code),
    CONSTRAINT ck_t_fin_invest_tipo   CHECK (tipo IN ('CDB','LCI','LCA','TESOURO_DIRETO','ACOES','FII','FUNDO','CRIPTO','OUTRO')),
    CONSTRAINT ck_t_fin_invest_valor  CHECK (valor_aplicado > 0),
    CONSTRAINT ck_t_fin_invest_status CHECK (status IN ('ATIVO','RESGATADO')),
    CONSTRAINT ck_t_fin_invest_datas  CHECK (data_vencimento IS NULL OR data_vencimento >= data_aplicacao)
);

CREATE TABLE t_fin_snapshots_financeiros (
    snapshot_financeiro_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    snapshot_financeiro_code  VARCHAR2(6)  NOT NULL,
    usuario_id                NUMBER       NOT NULL,
    usuario_code              VARCHAR2(6)  NOT NULL,
    conta_id                  NUMBER,
    conta_code                VARCHAR2(6),
    ano                       NUMBER(4)    NOT NULL,
    mes                       NUMBER(2)    NOT NULL,
    saldo_inicial             NUMBER(15,2) NOT NULL,
    total_receitas            NUMBER(15,2) DEFAULT 0 NOT NULL,
    total_gastos              NUMBER(15,2) DEFAULT 0 NOT NULL,
    saldo_final               NUMBER(15,2) NOT NULL,
    fechado                   CHAR(1)      DEFAULT 'N' NOT NULL,
    fechado_em                TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_t_fin_snapshots_financeiros PRIMARY KEY (snapshot_financeiro_id),
    CONSTRAINT uk_t_fin_snapshots_code UNIQUE (snapshot_financeiro_code),
    CONSTRAINT fk_t_fin_snapshots_usuario FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES t_fin_usuarios (usuario_id, usuario_code),
    CONSTRAINT fk_t_fin_snapshots_conta FOREIGN KEY (conta_id, conta_code)
        REFERENCES t_fin_contas_financeiras (conta_id, conta_code),
    CONSTRAINT ck_t_fin_snapshots_mes     CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_t_fin_snapshots_fechado CHECK (fechado IN ('S','N'))
);

-- Sem FK física (usuario_id é só escopo, como no projeto atual).
CREATE TABLE t_fin_aprendizado_classificacao (
    aprendizado_classificacao_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    aprendizado_classificacao_code  VARCHAR2(6)   NOT NULL,
    usuario_id                      NUMBER        NOT NULL,
    chave                           VARCHAR2(120) NOT NULL,
    tipo                            VARCHAR2(10)  NOT NULL,
    categoria_id                    NUMBER,
    categoria_code                  VARCHAR2(6),
    acertos                         NUMBER(10)    DEFAULT 0 NOT NULL,
    erros                           NUMBER(10)    DEFAULT 0 NOT NULL,
    atualizado_em                   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_t_fin_aprendizado_class PRIMARY KEY (aprendizado_classificacao_id),
    CONSTRAINT uk_t_fin_aprend_class_code UNIQUE (aprendizado_classificacao_code),
    CONSTRAINT uk_t_fin_aprend_class_chave UNIQUE (usuario_id, chave),
    CONSTRAINT ck_t_fin_aprend_class_tipo CHECK (tipo IN ('RECEITA','GASTO'))
);


-- ─────────────────────────────────────────────
--  IMPORTAÇÃO DE EXTRATOS
-- ─────────────────────────────────────────────
CREATE TABLE t_fin_extratos (
    extrato_id               NUMBER GENERATED BY DEFAULT AS IDENTITY,
    extrato_code             VARCHAR2(6)   NOT NULL,
    usuario_id               NUMBER        NOT NULL,
    usuario_code             VARCHAR2(6)   NOT NULL,
    conta_id                 NUMBER        NOT NULL,
    conta_code               VARCHAR2(6)   NOT NULL,
    transacao_id             NUMBER,
    transacao_code           VARCHAR2(6),
    arquivo_nome             VARCHAR2(255),
    arquivo_uuid             VARCHAR2(255) NOT NULL,
    hash_arquivo             VARCHAR2(64)  NOT NULL,
    banco_detectado          VARCHAR2(100),
    parser_versao_id         NUMBER,
    parser_versao_code       VARCHAR2(6),
    score_extracao           NUMBER(4,3),
    periodo_inicio           DATE,
    periodo_fim              DATE,
    status                   VARCHAR2(30)  DEFAULT 'upload_recebido' NOT NULL,
    total_lancamentos        NUMBER(10)    DEFAULT 0 NOT NULL,
    lancamentos_confirmados  NUMBER(10)    DEFAULT 0 NOT NULL,
    lancamentos_pendentes    NUMBER(10)    DEFAULT 0 NOT NULL,
    lancamentos_ignorados    NUMBER(10)    DEFAULT 0 NOT NULL,
    versao                   NUMBER(10)    DEFAULT 1 NOT NULL,
    criado_em                TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    atualizado_em            TIMESTAMP WITH TIME ZONE,
    ind_delete               VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    deleted_at               TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_t_fin_extratos PRIMARY KEY (extrato_id),
    CONSTRAINT uk_t_fin_extratos_code    UNIQUE (extrato_code),
    CONSTRAINT uk_t_fin_extratos_id_code UNIQUE (extrato_id, extrato_code),
    CONSTRAINT fk_t_fin_extratos_usuario FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES t_fin_usuarios (usuario_id, usuario_code),
    CONSTRAINT fk_t_fin_extratos_conta FOREIGN KEY (conta_id, conta_code)
        REFERENCES t_fin_contas_financeiras (conta_id, conta_code),
    CONSTRAINT fk_t_fin_extratos_transacao FOREIGN KEY (transacao_id, transacao_code)
        REFERENCES t_fin_transacoes (transacoes_id, transacoes_code),
    CONSTRAINT fk_t_fin_extratos_parser FOREIGN KEY (parser_versao_id, parser_versao_code)
        REFERENCES t_fin_parser_versoes (parser_versao_id, parser_versao_code),
    CONSTRAINT ck_t_fin_extratos_status CHECK (status IN (
        'upload_recebido','validando','na_fila','extraindo','classificando','aguardando_ia',
        'pendente_revisao','parcialmente_revisado','concluido','erro_formato','erro_extracao',
        'erro_classificacao','erro_timeout','cancelado','reprocessando')),
    CONSTRAINT ck_t_fin_extratos_ind_delete CHECK (ind_delete IN ('S','N'))
);

CREATE TABLE t_fin_processamento_jobs (
    processamento_job_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    processamento_job_code  VARCHAR2(6)  NOT NULL,
    extrato_id              NUMBER       NOT NULL,
    extrato_code            VARCHAR2(6)  NOT NULL,
    tipo                    VARCHAR2(30) NOT NULL,
    status                  VARCHAR2(30) DEFAULT 'enfileirado' NOT NULL,
    tentativas              NUMBER(3)    DEFAULT 0 NOT NULL,
    max_tentativas          NUMBER(3)    DEFAULT 3 NOT NULL,
    payload                 VARCHAR2(4000),
    erro_mensagem           VARCHAR2(4000),
    worker_id               VARCHAR2(100),
    lock_expires_at         TIMESTAMP WITH TIME ZONE,
    correlation_id          NUMBER,
    enfileirado_em          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    iniciado_em             TIMESTAMP WITH TIME ZONE,
    concluido_em            TIMESTAMP WITH TIME ZONE,
    proximo_retry           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_t_fin_processamento_jobs PRIMARY KEY (processamento_job_id),
    CONSTRAINT uk_t_fin_jobs_code UNIQUE (processamento_job_code),
    CONSTRAINT fk_t_fin_jobs_extrato FOREIGN KEY (extrato_id, extrato_code)
        REFERENCES t_fin_extratos (extrato_id, extrato_code),
    CONSTRAINT ck_t_fin_jobs_tipo CHECK (tipo IN (
        'extracao_pdf','classificacao_ia','notificacao','geracao_pdf','snapshot','anonimizacao')),
    CONSTRAINT ck_t_fin_jobs_status CHECK (status IN (
        'enfileirado','iniciando','processando','aguardando_ia','concluido','falha_ia',
        'falha_parser','timeout','retry_1','retry_2','retry_3','dead_letter','cancelado'))
);


-- ─────────────────────────────────────────────
--  USUÁRIO: SEGURANÇA, LGPD, NOTIFICAÇÕES E AUDITORIA
-- ─────────────────────────────────────────────
CREATE TABLE t_fin_consentimentos_lgpd (
    consentimento_lgpd_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    consentimento_lgpd_code  VARCHAR2(6)  NOT NULL,
    usuario_id               NUMBER       NOT NULL,
    usuario_code             VARCHAR2(6)  NOT NULL,
    tipo                     VARCHAR2(50) NOT NULL,
    versao_politica          VARCHAR2(20) NOT NULL,
    consentido               CHAR(1)      NOT NULL,
    ip_origem                VARCHAR2(45),
    criado_em                TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    revogado_em              TIMESTAMP WITH TIME ZONE,
    revogado_motivo          VARCHAR2(4000),
    CONSTRAINT pk_t_fin_consentimentos_lgpd PRIMARY KEY (consentimento_lgpd_id),
    CONSTRAINT uk_t_fin_lgpd_code UNIQUE (consentimento_lgpd_code),
    CONSTRAINT fk_t_fin_lgpd_usuario FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES t_fin_usuarios (usuario_id, usuario_code),
    CONSTRAINT ck_t_fin_lgpd_tipo CHECK (tipo IN (
        'tratamento_dados_financeiros','uso_ia','armazenamento_extrato','bot_whatsapp','bot_telegram')),
    CONSTRAINT ck_t_fin_lgpd_consentido CHECK (consentido IN ('S','N'))
);

CREATE TABLE t_fin_notificacoes (
    notificacao_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    notificacao_code  VARCHAR2(6)   NOT NULL,
    usuario_id        NUMBER        NOT NULL,
    usuario_code      VARCHAR2(6)   NOT NULL,
    canal             VARCHAR2(20)  NOT NULL,
    tipo              VARCHAR2(50)  NOT NULL,
    titulo            VARCHAR2(255),
    mensagem          VARCHAR2(4000),
    enviada           CHAR(1)       DEFAULT 'N' NOT NULL,
    enviada_em        TIMESTAMP WITH TIME ZONE,
    erro              VARCHAR2(4000),
    tentativas        NUMBER(3)     DEFAULT 0 NOT NULL,
    criado_em         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_t_fin_notificacoes PRIMARY KEY (notificacao_id),
    CONSTRAINT uk_t_fin_notificacoes_code UNIQUE (notificacao_code),
    CONSTRAINT fk_t_fin_notificacoes_usuario FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES t_fin_usuarios (usuario_id, usuario_code),
    CONSTRAINT ck_t_fin_notificacoes_canal   CHECK (canal IN ('whatsapp','telegram','email')),
    CONSTRAINT ck_t_fin_notificacoes_enviada CHECK (enviada IN ('S','N'))
);

CREATE TABLE t_fin_sessao_tokens (
    sessao_token_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sessao_token_code  VARCHAR2(6)   NOT NULL,
    token              VARCHAR2(255) NOT NULL,
    usuario_id         NUMBER        NOT NULL,
    usuario_code       VARCHAR2(6)   NOT NULL,
    criado_em          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    expira_em          TIMESTAMP     NOT NULL,
    CONSTRAINT pk_t_fin_sessao_tokens PRIMARY KEY (sessao_token_id),
    CONSTRAINT uk_t_fin_sessao_tokens_code  UNIQUE (sessao_token_code),
    CONSTRAINT uk_t_fin_sessao_tokens_token UNIQUE (token),
    CONSTRAINT fk_t_fin_sessao_tokens_usuario FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES t_fin_usuarios (usuario_id, usuario_code)
);

-- entidade_id é polimórfico (aponta para tabelas diferentes conforme "entidade"),
-- por isso não tem FK física.
CREATE TABLE t_fin_auditoria_eventos (
    auditoria_evento_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    auditoria_evento_code  VARCHAR2(6)  NOT NULL,
    correlation_id         NUMBER       NOT NULL,
    usuario_id             NUMBER,
    usuario_code           VARCHAR2(6),
    entidade               VARCHAR2(50) NOT NULL,
    entidade_id            NUMBER       NOT NULL,
    acao                   VARCHAR2(30) NOT NULL,
    dados_anteriores       VARCHAR2(4000),
    dados_novos            VARCHAR2(4000),
    ip_origem              VARCHAR2(45),
    user_agent             VARCHAR2(4000),
    origem                 VARCHAR2(20),
    criado_em              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_t_fin_auditoria_eventos PRIMARY KEY (auditoria_evento_id),
    CONSTRAINT uk_t_fin_auditoria_code UNIQUE (auditoria_evento_code),
    CONSTRAINT fk_t_fin_auditoria_usuario FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES t_fin_usuarios (usuario_id, usuario_code),
    CONSTRAINT ck_t_fin_auditoria_acao CHECK (acao IN (
        'CREATE','UPDATE','DELETE','LOGIN','LOGOUT','UPLOAD','CLASSIFY','CONFIRM',
        'REJECT','EXPORT','REPROCESS','API_KEY_GEN','PASSWORD_CHANGE','CANCEL')),
    CONSTRAINT ck_t_fin_auditoria_origem CHECK (origem IN ('web','bot_whatsapp','bot_telegram','api','sistema'))
);


-- ─────────────────────────────────────────────
--  ÍNDICES DAS CONSULTAS DA ATIVIDADE
-- ─────────────────────────────────────────────
CREATE INDEX ix_t_fin_contas_usuario     ON t_fin_contas_financeiras (usuario_id);
CREATE INDEX ix_t_fin_transacoes_conta   ON t_fin_transacoes (conta_id, data_transacao);
CREATE INDEX ix_t_fin_invest_usuario     ON t_fin_investimentos (usuario_id, data_aplicacao);


-- ─────────────────────────────────────────────
--  CARGA DE DOMÍNIO (bancos e categorias usados pelas FKs)
-- ─────────────────────────────────────────────
INSERT INTO t_fin_bancos (banco_code, nome) VALUES ('BCO001', 'Banco do Brasil');
INSERT INTO t_fin_bancos (banco_code, nome) VALUES ('BCO260', 'Nubank');
INSERT INTO t_fin_bancos (banco_code, nome) VALUES ('BCO341', 'Itaú Unibanco');

INSERT INTO t_fin_categorias (categoria_code, nome, tipo, padrao) VALUES ('CAT001', 'Salário', 'RECEITA', 'S');
INSERT INTO t_fin_categorias (categoria_code, nome, tipo, padrao) VALUES ('CAT002', 'Freelance', 'RECEITA', 'S');
INSERT INTO t_fin_categorias (categoria_code, nome, tipo, padrao) VALUES ('CAT003', 'Alimentação', 'GASTO', 'S');
INSERT INTO t_fin_categorias (categoria_code, nome, tipo, padrao) VALUES ('CAT004', 'Moradia', 'GASTO', 'S');
INSERT INTO t_fin_categorias (categoria_code, nome, tipo, padrao) VALUES ('CAT005', 'Transferências', 'AMBOS', 'S');

INSERT INTO t_fin_motivos_cancelamento (motivo_code, descricao) VALUES ('MOT001', 'Lançamento duplicado');
INSERT INTO t_fin_motivos_cancelamento (motivo_code, descricao) VALUES ('MOT002', 'Valor incorreto');
COMMIT;
