spring:
  application:
    name: fintech_app
  profiles:
    active: ${SPRING_PROFILE:dev}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
