-- ============================================================
--  FINAPP v2 — Schema refatorado
--  PostgreSQL 14+
--
--  MUDANÇAS vs v1:
--    • IDs: UUID → BIGINT GENERATED BY DEFAULT AS IDENTITY
--    • Toda tabela possui [tabela]_code VARCHAR(6) UNIQUE
--    • Chaves primárias compostas: (id_[tabela], [tabela]_code)
--    • FKs compostas em todas as referências
--    • categorias: removidos categoria_pai_id e usuario_id
--    • NOVA: categorias_pai       — hierarquia pai/filho
--    • NOVA: categorias_do_usuario — vínculo usuario ↔ categoria
--    • NOVA: motivos_cancelamento  — catálogo de motivos
--    • NOVA: transacoes_canceladas — log de cancelamentos
--    • REMOVIDAS: classificacao_logs, regras_classificacao
-- ============================================================

-- ─────────────────────────────────────────────
-- 0. EXTENSÕES + FUNÇÃO GERADORA DE CODE
-- ─────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "citext";

-- Gera um código alfanumérico maiúsculo de 6 caracteres
-- Usado como DEFAULT em todos os campos [tabela]_code
CREATE OR REPLACE FUNCTION generate_code()
RETURNS VARCHAR(6)
LANGUAGE sql
VOLATILE
AS $$
  SELECT upper(
    substring(
      md5(random()::text || clock_timestamp()::text),
      1, 6
    )
  );
$$;


-- ─────────────────────────────────────────────
-- SEQUÊNCIA COMPARTILHADA — auditoria_eventos
-- (tabela particionada não suporta IDENTITY nativo)
-- ─────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS auditoria_eventos_id_seq AS BIGINT;

-- Sequência para correlation_id — identifica um fluxo distribuído de ponta a ponta.
-- Cada requisição/operação gera um nextval único; todos os eventos do mesmo fluxo
-- compartilham o mesmo correlation_id, permitindo rastreio entre microsserviços.
CREATE SEQUENCE IF NOT EXISTS correlation_id_seq AS BIGINT;


-- ═══════════════════════════════════════════════════════════════
--  TABELAS
-- ═══════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────
-- 1. parser_versoes
-- ─────────────────────────────────────────────
CREATE TABLE parser_versoes (
    id_parser_versoes    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    parser_versoes_code  VARCHAR(6)   NOT NULL UNIQUE DEFAULT generate_code(),
    banco                VARCHAR(100) NOT NULL,
    versao               VARCHAR(20)  NOT NULL,
    ativo                BOOLEAN      NOT NULL DEFAULT TRUE,
    score_qualidade      NUMERIC(4,3),
    total_usos           INT          NOT NULL DEFAULT 0,
    total_erros          INT          NOT NULL DEFAULT 0,
    descricao            TEXT,
    depreciado_em        TIMESTAMPTZ,
    CONSTRAINT pk_parser_versoes     PRIMARY KEY (id_parser_versoes, parser_versoes_code),
    CONSTRAINT uq_parser_banco_versao UNIQUE (banco, versao)
);


-- ─────────────────────────────────────────────
-- 2. usuarios
-- ─────────────────────────────────────────────
CREATE TABLE usuarios (
    id_usuarios              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    usuarios_code            VARCHAR(6)   NOT NULL UNIQUE DEFAULT generate_code(),
    -- identificador de negócio legível (FIN-XXXXXX)
    codigo                   VARCHAR(12)  UNIQUE NOT NULL,
    cpf                      VARCHAR(255) NOT NULL,             -- AES-256 em repouso
    cpf_hash                 VARCHAR(64)  UNIQUE,               -- SHA-256 para lookup
    nome_completo            VARCHAR(150) NOT NULL,
    email                    VARCHAR(255) UNIQUE NOT NULL,
    senha_hash               VARCHAR(255) NOT NULL,             -- bcrypt
    telefone                 VARCHAR(20),
    telegram_chat_id         BIGINT,
    whatsapp_id              VARCHAR(100),
    saldo_inicial_definido   BOOLEAN      NOT NULL DEFAULT FALSE,
    moeda                    CHAR(3)      NOT NULL DEFAULT 'BRL',
    ativo                    BOOLEAN      NOT NULL DEFAULT TRUE,
    email_verificado         BOOLEAN      NOT NULL DEFAULT FALSE,
    token_verificacao        VARCHAR(100),
    token_verificacao_expira TIMESTAMPTZ,
    ultimo_login             TIMESTAMPTZ,
    tentativas_login         SMALLINT     NOT NULL DEFAULT 0,
    bloqueado_ate            TIMESTAMPTZ,
    refresh_token_hash       VARCHAR(255),
    api_key_hash             VARCHAR(255),
    deleted_at               TIMESTAMPTZ,
    versao                   INT          NOT NULL DEFAULT 1,
    criado_em                TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em            TIMESTAMPTZ,
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuarios, usuarios_code)
);


-- ─────────────────────────────────────────────
-- 3. contas_financeiras
-- ─────────────────────────────────────────────
CREATE TABLE contas_financeiras (
    id_contas_financeiras   BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    contas_financeiras_code VARCHAR(6)    NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → usuarios
    usuario_id              BIGINT        NOT NULL,
    usuario_code            VARCHAR(6)    NOT NULL,
    nome                    VARCHAR(100)  NOT NULL,
    tipo                    VARCHAR(20)   NOT NULL
                                CHECK (tipo IN ('corrente','poupanca','cartao','dinheiro','investimento')),
    banco                   VARCHAR(100),
    saldo_inicial           NUMERIC(15,2) NOT NULL DEFAULT 0,
    padrao                  BOOLEAN       DEFAULT FALSE,
    ativa                   BOOLEAN       DEFAULT TRUE,
    criado_em               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    atualizado_em           TIMESTAMPTZ,
    CONSTRAINT pk_contas_financeiras PRIMARY KEY (id_contas_financeiras, contas_financeiras_code),
    CONSTRAINT fk_contas_usuario
        FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES usuarios(id_usuarios, usuarios_code)
        ON DELETE CASCADE
);


-- ─────────────────────────────────────────────
-- 4. categorias
--    • SEM categoria_pai_id  → ver categorias_pai
--    • SEM usuario_id        → ver categorias_do_usuario
-- ─────────────────────────────────────────────
CREATE TABLE categorias (
    id_categorias    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    categorias_code  VARCHAR(6)   NOT NULL UNIQUE DEFAULT generate_code(),
    nome             VARCHAR(100) NOT NULL,
    tipo             VARCHAR(10)  NOT NULL CHECK (tipo IN ('receita','gasto','ambos')),
    icone            VARCHAR(50),
    cor_hex          CHAR(7),
    padrao           BOOLEAN      DEFAULT FALSE,  -- TRUE = categoria global imutável
    criado_em        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_categorias PRIMARY KEY (id_categorias, categorias_code)
);


-- ─────────────────────────────────────────────
-- 5. categorias_pai
--    Tabela de hierarquia: registra qual categoria é pai de outra.
--    Uma categoria pode ter apenas 1 pai (relação muitos-para-um).
-- ─────────────────────────────────────────────
CREATE TABLE categorias_pai (
    id_categorias_pai    BIGINT     GENERATED BY DEFAULT AS IDENTITY,
    categorias_pai_code  VARCHAR(6) NOT NULL UNIQUE DEFAULT generate_code(),
    -- categoria filha
    categoria_id         BIGINT     NOT NULL,
    categoria_code       VARCHAR(6) NOT NULL,
    -- categoria pai
    pai_id               BIGINT     NOT NULL,
    pai_code             VARCHAR(6) NOT NULL,
    criado_em            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_categorias_pai PRIMARY KEY (id_categorias_pai, categorias_pai_code),
    CONSTRAINT fk_catpai_filho
        FOREIGN KEY (categoria_id, categoria_code)
        REFERENCES categorias(id_categorias, categorias_code)
        ON DELETE CASCADE,
    CONSTRAINT fk_catpai_pai
        FOREIGN KEY (pai_id, pai_code)
        REFERENCES categorias(id_categorias, categorias_code)
        ON DELETE CASCADE,
    -- uma categoria só pode ter um pai
    CONSTRAINT uq_catpai_filho UNIQUE (categoria_id, categoria_code),
    -- evita auto-referência
    CONSTRAINT ck_catpai_no_self CHECK (categoria_id <> pai_id)
);


-- ─────────────────────────────────────────────
-- 6. categorias_do_usuario
--    Tabela de vínculo entre usuário e categorias.
--    Inclui tanto as globais visíveis quanto as criadas pelo usuário.
-- ─────────────────────────────────────────────
CREATE TABLE categorias_do_usuario (
    id_categorias_do_usuario    BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    categorias_do_usuario_code  VARCHAR(6)  NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → usuarios
    usuario_id                  BIGINT      NOT NULL,
    usuario_code                VARCHAR(6)  NOT NULL,
    -- FK composta → categorias
    categoria_id                BIGINT      NOT NULL,
    categoria_code              VARCHAR(6)  NOT NULL,
    ativa                       BOOLEAN     NOT NULL DEFAULT TRUE,
    criado_em                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_cat_usuario PRIMARY KEY (id_categorias_do_usuario, categorias_do_usuario_code),
    CONSTRAINT fk_catuser_usuario
        FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES usuarios(id_usuarios, usuarios_code)
        ON DELETE CASCADE,
    CONSTRAINT fk_catuser_categoria
        FOREIGN KEY (categoria_id, categoria_code)
        REFERENCES categorias(id_categorias, categorias_code)
        ON DELETE CASCADE,
    -- cada categoria aparece uma única vez por usuário
    CONSTRAINT uq_catuser_par UNIQUE (usuario_id, usuario_code, categoria_id, categoria_code)
);


-- ─────────────────────────────────────────────
-- 7. categoria_thresholds
-- ─────────────────────────────────────────────
CREATE TABLE categoria_thresholds (
    id_categoria_thresholds    BIGINT     GENERATED BY DEFAULT AS IDENTITY,
    categoria_thresholds_code  VARCHAR(6) NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → categorias
    categoria_id               BIGINT     NOT NULL,
    categoria_code             VARCHAR(6) NOT NULL,
    threshold_auto             SMALLINT   NOT NULL DEFAULT 70  CHECK (threshold_auto   BETWEEN 0 AND 100),
    threshold_alerta           SMALLINT   NOT NULL DEFAULT 50  CHECK (threshold_alerta BETWEEN 0 AND 100),
    ambiguidade_alta           BOOLEAN    NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_cat_thresholds PRIMARY KEY (id_categoria_thresholds, categoria_thresholds_code),
    CONSTRAINT fk_catthresh_categoria
        FOREIGN KEY (categoria_id, categoria_code)
        REFERENCES categorias(id_categorias, categorias_code)
        ON DELETE CASCADE,
    -- um threshold por categoria
    CONSTRAINT uq_catthresh_cat UNIQUE (categoria_id, categoria_code)
);


-- ─────────────────────────────────────────────
-- 8. extratos
-- ─────────────────────────────────────────────
CREATE TABLE extratos (
    id_extratos                  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    extratos_code                VARCHAR(6)    NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → usuarios
    usuario_id                   BIGINT        NOT NULL,
    usuario_code                 VARCHAR(6)    NOT NULL,
    -- FK composta → contas_financeiras
    conta_id                     BIGINT        NOT NULL,
    conta_code                   VARCHAR(6)    NOT NULL,
    arquivo_nome                 VARCHAR(255),
    arquivo_uuid                 VARCHAR(255)  NOT NULL,
    hash_arquivo                 VARCHAR(64)   NOT NULL,
    banco_detectado              VARCHAR(100),
    -- FK composta → parser_versoes (nullable)
    parser_versao_id             BIGINT,
    parser_versao_code           VARCHAR(6),
    score_extracao               NUMERIC(4,3),
    periodo_inicio               DATE,
    periodo_fim                  DATE,
    status                       VARCHAR(30)   NOT NULL DEFAULT 'upload_recebido'
                                     CHECK (status IN (
                                         'upload_recebido','validando','na_fila','extraindo',
                                         'classificando','aguardando_ia','pendente_revisao',
                                         'parcialmente_revisado','concluido','erro_formato',
                                         'erro_extracao','erro_classificacao','erro_timeout',
                                         'cancelado','reprocessando'
                                     )),
    total_lancamentos            INT           NOT NULL DEFAULT 0,
    lancamentos_confirmados      INT           NOT NULL DEFAULT 0,
    lancamentos_pendentes        INT           NOT NULL DEFAULT 0,
    lancamentos_ignorados        INT           NOT NULL DEFAULT 0,
    versao                       INT           NOT NULL DEFAULT 1,
    criado_em                    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    atualizado_em                TIMESTAMPTZ,
    CONSTRAINT pk_extratos PRIMARY KEY (id_extratos, extratos_code),
    CONSTRAINT fk_extratos_usuario
        FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES usuarios(id_usuarios, usuarios_code)
        ON DELETE CASCADE,
    CONSTRAINT fk_extratos_conta
        FOREIGN KEY (conta_id, conta_code)
        REFERENCES contas_financeiras(id_contas_financeiras, contas_financeiras_code),
    CONSTRAINT fk_extratos_parser
        FOREIGN KEY (parser_versao_id, parser_versao_code)
        REFERENCES parser_versoes(id_parser_versoes, parser_versoes_code)
);


-- ─────────────────────────────────────────────
-- 9. transacoes
-- ─────────────────────────────────────────────
CREATE TABLE transacoes (
    id_transacoes              BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    transacoes_code            VARCHAR(6)    NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → usuarios
    usuario_id                 BIGINT        NOT NULL,
    usuario_code               VARCHAR(6)    NOT NULL,
    -- FK composta → contas_financeiras
    conta_id                   BIGINT        NOT NULL,
    conta_code                 VARCHAR(6)    NOT NULL,
    -- FK composta → extratos (nullable)
    extrato_id                 BIGINT,
    extrato_code               VARCHAR(6),
    -- auto-referência para estorno (nullable)
    transacao_estorno_id       BIGINT,
    transacao_estorno_code     VARCHAR(6),
    tipo                       VARCHAR(10)   NOT NULL CHECK (tipo IN ('receita','gasto')),
    descricao_original         TEXT,
    descricao_usuario          VARCHAR(255),
    descricao_normalizada      VARCHAR(255),
    valor                      NUMERIC(15,2) NOT NULL CHECK (valor > 0),
    data_transacao             DATE          NOT NULL,
    data_lancamento            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    -- FK composta → categorias (nullable)
    categoria_id               BIGINT,
    categoria_code             VARCHAR(6),
    subcategoria               VARCHAR(100),
    estabelecimento            VARCHAR(255),
    origem                     VARCHAR(20)   NOT NULL DEFAULT 'manual'
                                   CHECK (origem IN ('manual','pdf','api')),
    status_revisao             VARCHAR(30)   NOT NULL DEFAULT 'extraida'
                                   CHECK (status_revisao IN (
                                       'extraida','classificada','pendente_revisao',
                                       'confirmada','ignorada','arquivada'
                                   )),
    confianca_ia               SMALLINT      CHECK (confianca_ia BETWEEN 0 AND 100),
    recorrente                 BOOLEAN       DEFAULT FALSE,
    periodo_recorrencia        VARCHAR(20),
    observacao                 TEXT,
    deleted_at                 TIMESTAMPTZ,
    versao                     INT           NOT NULL DEFAULT 1,
    criado_em                  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    atualizado_em              TIMESTAMPTZ,
    CONSTRAINT pk_transacoes PRIMARY KEY (id_transacoes, transacoes_code),
    CONSTRAINT fk_transacoes_usuario
        FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES usuarios(id_usuarios, usuarios_code)
        ON DELETE CASCADE,
    CONSTRAINT fk_transacoes_conta
        FOREIGN KEY (conta_id, conta_code)
        REFERENCES contas_financeiras(id_contas_financeiras, contas_financeiras_code),
    CONSTRAINT fk_transacoes_extrato
        FOREIGN KEY (extrato_id, extrato_code)
        REFERENCES extratos(id_extratos, extratos_code),
    CONSTRAINT fk_transacoes_estorno
        FOREIGN KEY (transacao_estorno_id, transacao_estorno_code)
        REFERENCES transacoes(id_transacoes, transacoes_code),
    CONSTRAINT fk_transacoes_categoria
        FOREIGN KEY (categoria_id, categoria_code)
        REFERENCES categorias(id_categorias, categorias_code)
);


-- ─────────────────────────────────────────────
-- 10. motivos_cancelamento
--     Catálogo de motivos pelo qual uma transação pode ser cancelada.
-- ─────────────────────────────────────────────
CREATE TABLE motivos_cancelamento (
    id_motivos_cancelamento    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    motivos_cancelamento_code  VARCHAR(6)   NOT NULL UNIQUE DEFAULT generate_code(),
    descricao                  VARCHAR(255) NOT NULL,
    -- quem pode acionar este motivo
    origem_permitida           VARCHAR(20)  NOT NULL DEFAULT 'todos'
                                   CHECK (origem_permitida IN ('usuario','sistema','admin','todos')),
    ativo                      BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_motivos_cancelamento PRIMARY KEY (id_motivos_cancelamento, motivos_cancelamento_code)
);


-- ─────────────────────────────────────────────
-- 11. transacoes_canceladas
--     Registra cada cancelamento de transação com rastreabilidade
--     completa: quem cancelou, por qual motivo e quando.
--     A transação original recebe deleted_at = NOW() ao ser cancelada.
-- ─────────────────────────────────────────────
CREATE TABLE transacoes_canceladas (
    id_transacoes_canceladas    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    transacoes_canceladas_code  VARCHAR(6)    NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → transacoes (a transação que foi cancelada)
    transacao_id                BIGINT        NOT NULL,
    transacao_code              VARCHAR(6)    NOT NULL,
    -- FK composta → usuarios
    usuario_id                  BIGINT        NOT NULL,
    usuario_code                VARCHAR(6)    NOT NULL,
    -- FK composta → contas_financeiras
    conta_id                    BIGINT        NOT NULL,
    conta_code                  VARCHAR(6)    NOT NULL,
    -- FK composta → motivos_cancelamento
    motivo_id                   BIGINT        NOT NULL,
    motivo_code                 VARCHAR(6)    NOT NULL,
    -- quem executou o cancelamento
    cancelado_por               VARCHAR(20)   NOT NULL DEFAULT 'usuario'
                                    CHECK (cancelado_por IN ('usuario','sistema','admin')),
    valor_original              NUMERIC(15,2) NOT NULL,   -- cópia do valor no momento do cancelamento
    observacao                  TEXT,
    ip_origem                   INET,
    cancelado_em                TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    -- uma transação só pode ser cancelada uma vez
    CONSTRAINT pk_transacoes_canceladas PRIMARY KEY (id_transacoes_canceladas, transacoes_canceladas_code),
    CONSTRAINT fk_txcanc_transacao
        FOREIGN KEY (transacao_id, transacao_code)
        REFERENCES transacoes(id_transacoes, transacoes_code),
    CONSTRAINT fk_txcanc_usuario
        FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES usuarios(id_usuarios, usuarios_code),
    CONSTRAINT fk_txcanc_conta
        FOREIGN KEY (conta_id, conta_code)
        REFERENCES contas_financeiras(id_contas_financeiras, contas_financeiras_code),
    CONSTRAINT fk_txcanc_motivo
        FOREIGN KEY (motivo_id, motivo_code)
        REFERENCES motivos_cancelamento(id_motivos_cancelamento, motivos_cancelamento_code),
    CONSTRAINT uq_txcanc_transacao UNIQUE (transacao_id, transacao_code)
);


-- ─────────────────────────────────────────────
-- 12. processamento_jobs
-- ─────────────────────────────────────────────
CREATE TABLE processamento_jobs (
    id_processamento_jobs    BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    processamento_jobs_code  VARCHAR(6)  NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → extratos (nullable)
    extrato_id               BIGINT,
    extrato_code             VARCHAR(6),
    tipo                     VARCHAR(30) NOT NULL CHECK (tipo IN (
                                 'extracao_pdf','classificacao_ia','notificacao',
                                 'geracao_pdf','snapshot','anonimizacao'
                             )),
    status                   VARCHAR(30) NOT NULL DEFAULT 'enfileirado' CHECK (status IN (
                                 'enfileirado','iniciando','processando','aguardando_ia',
                                 'concluido','falha_ia','falha_parser','timeout',
                                 'retry_1','retry_2','retry_3','dead_letter','cancelado'
                             )),
    tentativas               SMALLINT    NOT NULL DEFAULT 0,
    max_tentativas           SMALLINT    NOT NULL DEFAULT 3,
    payload                  JSONB,
    erro_mensagem            TEXT,
    worker_id                VARCHAR(100),
    lock_expires_at          TIMESTAMPTZ,
    correlation_id           BIGINT,        -- rastreabilidade distribuída — nextval(correlation_id_seq)
    enfileirado_em           TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    iniciado_em              TIMESTAMPTZ,
    concluido_em             TIMESTAMPTZ,
    proximo_retry            TIMESTAMPTZ,
    CONSTRAINT pk_processamento_jobs PRIMARY KEY (id_processamento_jobs, processamento_jobs_code),
    CONSTRAINT fk_jobs_extrato
        FOREIGN KEY (extrato_id, extrato_code)
        REFERENCES extratos(id_extratos, extratos_code)
);


-- ─────────────────────────────────────────────
-- 13. snapshots_financeiros
-- ─────────────────────────────────────────────
CREATE TABLE snapshots_financeiros (
    id_snapshots_financeiros    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    snapshots_financeiros_code  VARCHAR(6)    NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → usuarios
    usuario_id                  BIGINT        NOT NULL,
    usuario_code                VARCHAR(6)    NOT NULL,
    -- FK composta → contas_financeiras (NULL = consolidado de todas as contas)
    conta_id                    BIGINT,
    conta_code                  VARCHAR(6),
    ano                         SMALLINT      NOT NULL,
    mes                         SMALLINT      NOT NULL CHECK (mes BETWEEN 1 AND 12),
    saldo_inicial               NUMERIC(15,2) NOT NULL,
    total_receitas              NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_gastos                NUMERIC(15,2) NOT NULL DEFAULT 0,
    saldo_final                 NUMERIC(15,2) NOT NULL,
    fechado                     BOOLEAN       NOT NULL DEFAULT FALSE,
    fechado_em                  TIMESTAMPTZ,
    CONSTRAINT pk_snapshots_financeiros PRIMARY KEY (id_snapshots_financeiros, snapshots_financeiros_code),
    CONSTRAINT fk_snap_usuario
        FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES usuarios(id_usuarios, usuarios_code)
        ON DELETE CASCADE,
    CONSTRAINT fk_snap_conta
        FOREIGN KEY (conta_id, conta_code)
        REFERENCES contas_financeiras(id_contas_financeiras, contas_financeiras_code)
);

-- Unicidade para snapshots com conta específica
CREATE UNIQUE INDEX uq_snapshot_com_conta
    ON snapshots_financeiros(usuario_id, conta_id, ano, mes)
    WHERE conta_id IS NOT NULL;

-- Unicidade para snapshot consolidado (conta NULL)
CREATE UNIQUE INDEX uq_snapshot_consolidado
    ON snapshots_financeiros(usuario_id, ano, mes)
    WHERE conta_id IS NULL;


-- ─────────────────────────────────────────────
-- 14. auditoria_eventos (tabela particionada por mês)
--     Usa sequência explícita pois IDENTITY não é suportado
--     diretamente em tabelas particionadas no PG 14.
--     A PK inclui criado_em (chave de partição — obrigatório).
--     IMUTÁVEL: nunca recebe UPDATE ou DELETE.
-- ─────────────────────────────────────────────
CREATE TABLE auditoria_eventos (
    id_auditoria_eventos    BIGINT      NOT NULL DEFAULT nextval('auditoria_eventos_id_seq'),
    auditoria_eventos_code  VARCHAR(6)  NOT NULL DEFAULT generate_code(),
    correlation_id          BIGINT      NOT NULL,           -- rastreabilidade distribuída — nextval(correlation_id_seq)
    -- FK composta → usuarios (nullable — eventos de sistema)
    usuario_id              BIGINT,
    usuario_code            VARCHAR(6),
    entidade                VARCHAR(50) NOT NULL,           -- ex: 'transacao', 'extrato'
    entidade_id             BIGINT      NOT NULL,           -- ID da entidade auditada
    acao                    VARCHAR(30) NOT NULL CHECK (acao IN (
                                'CREATE','UPDATE','DELETE','LOGIN','LOGOUT','UPLOAD',
                                'CLASSIFY','CONFIRM','REJECT','EXPORT','REPROCESS',
                                'API_KEY_GEN','PASSWORD_CHANGE','CANCEL'
                            )),
    dados_anteriores        JSONB,      -- snapshot before (NUNCA incluir CPF/senha/tokens)
    dados_novos             JSONB,      -- snapshot after
    ip_origem               INET,       -- último octeto mascarado
    user_agent              TEXT,
    origem                  VARCHAR(20) CHECK (origem IN ('web','bot_whatsapp','bot_telegram','api','sistema')),
    criado_em               TIMESTAMPTZ NOT NULL DEFAULT NOW(),   -- IMUTÁVEL
    CONSTRAINT pk_auditoria_eventos PRIMARY KEY (id_auditoria_eventos, auditoria_eventos_code, criado_em),
    CONSTRAINT fk_audit_usuario
        FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES usuarios(id_usuarios, usuarios_code)
) PARTITION BY RANGE (criado_em);

-- Partições 2025
CREATE TABLE auditoria_eventos_2025_01 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');
CREATE TABLE auditoria_eventos_2025_02 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');
CREATE TABLE auditoria_eventos_2025_03 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-03-01') TO ('2025-04-01');
CREATE TABLE auditoria_eventos_2025_04 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');
CREATE TABLE auditoria_eventos_2025_05 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');
CREATE TABLE auditoria_eventos_2025_06 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-06-01') TO ('2025-07-01');
CREATE TABLE auditoria_eventos_2025_07 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-07-01') TO ('2025-08-01');
CREATE TABLE auditoria_eventos_2025_08 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-08-01') TO ('2025-09-01');
CREATE TABLE auditoria_eventos_2025_09 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-09-01') TO ('2025-10-01');
CREATE TABLE auditoria_eventos_2025_10 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-10-01') TO ('2025-11-01');
CREATE TABLE auditoria_eventos_2025_11 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-11-01') TO ('2025-12-01');
CREATE TABLE auditoria_eventos_2025_12 PARTITION OF auditoria_eventos FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');
-- Partições 2026
CREATE TABLE auditoria_eventos_2026_01 PARTITION OF auditoria_eventos FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE auditoria_eventos_2026_02 PARTITION OF auditoria_eventos FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE auditoria_eventos_2026_03 PARTITION OF auditoria_eventos FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE auditoria_eventos_2026_04 PARTITION OF auditoria_eventos FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE auditoria_eventos_2026_05 PARTITION OF auditoria_eventos FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE auditoria_eventos_2026_06 PARTITION OF auditoria_eventos FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');


-- ─────────────────────────────────────────────
-- 15. consentimentos_lgpd
-- ─────────────────────────────────────────────
CREATE TABLE consentimentos_lgpd (
    id_consentimentos_lgpd    BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    consentimentos_lgpd_code  VARCHAR(6)  NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → usuarios
    usuario_id                BIGINT      NOT NULL,
    usuario_code              VARCHAR(6)  NOT NULL,
    tipo                      VARCHAR(50) NOT NULL CHECK (tipo IN (
                                  'tratamento_dados_financeiros','uso_ia',
                                  'armazenamento_extrato','bot_whatsapp','bot_telegram'
                              )),
    versao_politica           VARCHAR(20) NOT NULL,
    consentido                BOOLEAN     NOT NULL,
    ip_origem                 INET,
    criado_em                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revogado_em               TIMESTAMPTZ,
    revogado_motivo           TEXT,
    CONSTRAINT pk_consentimentos_lgpd PRIMARY KEY (id_consentimentos_lgpd, consentimentos_lgpd_code),
    CONSTRAINT fk_lgpd_usuario
        FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES usuarios(id_usuarios, usuarios_code)
        ON DELETE CASCADE
);


-- ─────────────────────────────────────────────
-- 16. notificacoes
-- ─────────────────────────────────────────────
CREATE TABLE notificacoes (
    id_notificacoes    BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    notificacoes_code  VARCHAR(6)  NOT NULL UNIQUE DEFAULT generate_code(),
    -- FK composta → usuarios
    usuario_id         BIGINT      NOT NULL,
    usuario_code       VARCHAR(6)  NOT NULL,
    canal              VARCHAR(20) NOT NULL CHECK (canal IN ('whatsapp','telegram','email')),
    tipo               VARCHAR(50) NOT NULL,
    titulo             VARCHAR(255),
    mensagem           TEXT,
    enviada            BOOLEAN     NOT NULL DEFAULT FALSE,
    enviada_em         TIMESTAMPTZ,
    erro               TEXT,
    tentativas         SMALLINT    NOT NULL DEFAULT 0,
    criado_em          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_notificacoes PRIMARY KEY (id_notificacoes, notificacoes_code),
    CONSTRAINT fk_notif_usuario
        FOREIGN KEY (usuario_id, usuario_code)
        REFERENCES usuarios(id_usuarios, usuarios_code)
        ON DELETE CASCADE
);


-- ═══════════════════════════════════════════════════════════════
--  ÍNDICES
-- ═══════════════════════════════════════════════════════════════

-- usuarios
CREATE INDEX idx_usuarios_email     ON usuarios(email)    WHERE deleted_at IS NULL;
CREATE INDEX idx_usuarios_cpf_hash  ON usuarios(cpf_hash) WHERE deleted_at IS NULL;
CREATE INDEX idx_usuarios_codigo    ON usuarios(codigo);

-- contas_financeiras
CREATE INDEX idx_contas_usuario     ON contas_financeiras(usuario_id);

-- categorias
CREATE INDEX idx_categorias_tipo    ON categorias(tipo);
CREATE INDEX idx_categorias_padrao  ON categorias(padrao) WHERE padrao = TRUE;

-- categorias_do_usuario
CREATE INDEX idx_catuser_usuario    ON categorias_do_usuario(usuario_id);
CREATE INDEX idx_catuser_categoria  ON categorias_do_usuario(categoria_id);

-- categorias_pai
CREATE INDEX idx_catpai_filho       ON categorias_pai(categoria_id);
CREATE INDEX idx_catpai_pai         ON categorias_pai(pai_id);

-- extratos
CREATE INDEX idx_extratos_usuario   ON extratos(usuario_id, criado_em DESC);
CREATE INDEX idx_extratos_hash      ON extratos(hash_arquivo);

-- transacoes
CREATE INDEX idx_transacoes_usuario ON transacoes(usuario_id, data_transacao DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_transacoes_conta   ON transacoes(conta_id);
CREATE INDEX idx_transacoes_cat     ON transacoes(categoria_id);
CREATE INDEX idx_transacoes_status  ON transacoes(status_revisao);
CREATE INDEX idx_transacoes_extrato ON transacoes(extrato_id) WHERE extrato_id IS NOT NULL;

-- transacoes_canceladas
CREATE INDEX idx_txcanc_transacao   ON transacoes_canceladas(transacao_id);
CREATE INDEX idx_txcanc_usuario     ON transacoes_canceladas(usuario_id);
CREATE INDEX idx_txcanc_motivo      ON transacoes_canceladas(motivo_id);

-- snapshots
CREATE INDEX idx_snap_usuario_mes   ON snapshots_financeiros(usuario_id, ano DESC, mes DESC);

-- auditoria_eventos (herdado pelas partições)
CREATE INDEX idx_audit_usuario      ON auditoria_eventos(usuario_id, criado_em DESC);
CREATE INDEX idx_audit_correlation  ON auditoria_eventos(correlation_id);
CREATE INDEX idx_audit_entidade     ON auditoria_eventos(entidade, entidade_id);


-- ═══════════════════════════════════════════════════════════════
--  SEED — PARSER_VERSOES
--  Codes fixos para referência estável
-- ═══════════════════════════════════════════════════════════════
INSERT INTO parser_versoes
    (id_parser_versoes, parser_versoes_code, banco, versao, ativo, score_qualidade, descricao)
VALUES
    (1, 'NUB001', 'Nubank',    'v1.0', TRUE,  0.980, 'Parser Nubank — extrato CSV/PDF'),
    (2, 'ITA002', 'Itaú',      'v1.0', TRUE,  0.960, 'Parser Itaú — PDF padrão'),
    (3, 'BRA003', 'Bradesco',  'v1.0', TRUE,  0.940, 'Parser Bradesco — PDF'),
    (4, 'SAN004', 'Santander', 'v1.0', TRUE,  0.920, 'Parser Santander — PDF'),
    (5, 'CAI005', 'Caixa',     'v1.0', TRUE,  0.900, 'Parser Caixa — PDF'),
    (6, 'INT006', 'Inter',     'v1.0', TRUE,  0.970, 'Parser Inter — CSV/PDF'),
    (7, 'XP0007', 'XP',        'v1.0', TRUE,  0.930, 'Parser XP Investimentos — PDF'),
    (8, 'GEN008', 'Genérico',  'v1.0', TRUE,  0.700, 'Parser genérico de fallback');

SELECT setval(pg_get_serial_sequence('parser_versoes','id_parser_versoes'), 8);


-- ═══════════════════════════════════════════════════════════════
--  SEED — CATEGORIAS GLOBAIS (padrao = TRUE)
--  IDs e codes fixos para referências estáveis em toda a aplicação
-- ═══════════════════════════════════════════════════════════════

-- ── Raiz: Receitas ────────────────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (1,  'SAL001', 'Salário',         'receita', '💰', '#16A34A', TRUE),
    (2,  'FRE002', 'Freelance',        'receita', '💻', '#0EA5E9', TRUE),
    (3,  'INV003', 'Investimentos',    'receita', '📈', '#7C3AED', TRUE),
    (4,  'ORC004', 'Outras Receitas',  'receita', '➕', '#64748B', TRUE);

-- ── Raiz: Gastos ──────────────────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (10, 'ALI010', 'Alimentação',  'gasto',  '🍽️', '#EF4444', TRUE),
    (11, 'TRA011', 'Transporte',   'gasto',  '🚗', '#F97316', TRUE),
    (12, 'MOR012', 'Moradia',      'gasto',  '🏠', '#FBBF24', TRUE),
    (13, 'SAU013', 'Saúde',        'gasto',  '🏥', '#EC4899', TRUE),
    (14, 'EDU014', 'Educação',     'gasto',  '📚', '#8B5CF6', TRUE),
    (15, 'LAZ015', 'Lazer',        'gasto',  '🎮', '#06B6D4', TRUE),
    (16, 'VES016', 'Vestuário',    'gasto',  '👗', '#F43F5E', TRUE),
    (17, 'ASS017', 'Assinaturas',  'gasto',  '📱', '#6366F1', TRUE),
    (18, 'FIN018', 'Financeiro',   'gasto',  '🏦', '#059669', TRUE),
    (19, 'STR019', 'Streaming',    'gasto',  '🎬', '#DC2626', TRUE),
    (20, 'OUT020', 'Outros',       'ambos',  '📦', '#94A3B8', TRUE);

-- ── Subcategorias: Alimentação ────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (101, 'SUP101', 'Supermercado', 'gasto', '🛒', '#EF4444', TRUE),
    (102, 'RES102', 'Restaurante',  'gasto', '🍴', '#EF4444', TRUE),
    (103, 'DEL103', 'Delivery',     'gasto', '🛵', '#EF4444', TRUE),
    (104, 'PAD104', 'Padaria/Café', 'gasto', '☕', '#EF4444', TRUE),
    (105, 'LAN105', 'Lanchonete',   'gasto', '🍔', '#EF4444', TRUE);

-- ── Subcategorias: Transporte ─────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (111, 'COM111', 'Combustível',        'gasto', '⛽', '#F97316', TRUE),
    (112, 'UBE112', 'Uber/99',            'gasto', '🚕', '#F97316', TRUE),
    (113, 'TPU113', 'Transporte Público', 'gasto', '🚌', '#F97316', TRUE),
    (114, 'EST114', 'Estacionamento',     'gasto', '🅿️', '#F97316', TRUE),
    (115, 'MAN115', 'Manutenção',         'gasto', '🔧', '#F97316', TRUE);

-- ── Subcategorias: Moradia ────────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (121, 'ALU121', 'Aluguel',     'gasto', '🔑', '#FBBF24', TRUE),
    (122, 'CON122', 'Condomínio',  'gasto', '🏢', '#FBBF24', TRUE),
    (123, 'ENE123', 'Energia',     'gasto', '💡', '#FBBF24', TRUE),
    (124, 'AGU124', 'Água',        'gasto', '💧', '#FBBF24', TRUE),
    (125, 'WEB125', 'Internet',    'gasto', '📶', '#FBBF24', TRUE),
    (126, 'GAS126', 'Gás',         'gasto', '🔥', '#FBBF24', TRUE);

-- ── Subcategorias: Saúde ──────────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (131, 'PLS131', 'Plano de Saúde', 'gasto', '🏥', '#EC4899', TRUE),
    (132, 'FAR132', 'Farmácia',       'gasto', '💊', '#EC4899', TRUE),
    (133, 'MED133', 'Consultas',      'gasto', '👨‍⚕️', '#EC4899', TRUE),
    (134, 'ACA134', 'Academia',       'gasto', '🏋️', '#EC4899', TRUE);

-- ── Subcategorias: Educação ───────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (141, 'MEN141', 'Mensalidade',  'gasto', '🎓', '#8B5CF6', TRUE),
    (142, 'CUR142', 'Cursos Online','gasto', '💡', '#8B5CF6', TRUE),
    (143, 'LIV143', 'Livros',       'gasto', '📖', '#8B5CF6', TRUE);

-- ── Subcategorias: Lazer ──────────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (151, 'CIN151', 'Cinema/Teatro', 'gasto', '🎭', '#06B6D4', TRUE),
    (152, 'JOG152', 'Jogos',         'gasto', '🕹️', '#06B6D4', TRUE),
    (153, 'VIA153', 'Viagem',        'gasto', '✈️', '#06B6D4', TRUE),
    (154, 'BAR154', 'Bares/Baladas', 'gasto', '🍻', '#06B6D4', TRUE);

-- ── Subcategorias: Assinaturas ────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (171, 'CEL171', 'Celular',          'gasto', '📲', '#6366F1', TRUE),
    (172, 'SOF172', 'Softwares',        'gasto', '🖥️', '#6366F1', TRUE),
    (173, 'CLU173', 'Clubes/Serviços',  'gasto', '🔄', '#6366F1', TRUE);

-- ── Subcategorias: Streaming ──────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (191, 'NET191', 'Netflix',        'gasto', '🎬', '#DC2626', TRUE),
    (192, 'SPO192', 'Spotify',        'gasto', '🎵', '#DC2626', TRUE),
    (193, 'YOU193', 'YouTube Premium','gasto', '▶️', '#DC2626', TRUE),
    (194, 'DIS194', 'Disney+',        'gasto', '🏰', '#DC2626', TRUE),
    (195, 'AMA195', 'Amazon Prime',   'gasto', '📦', '#DC2626', TRUE);

-- ── Subcategorias: Financeiro ─────────────────────────────────
INSERT INTO categorias (id_categorias, categorias_code, nome, tipo, icone, cor_hex, padrao) VALUES
    (181, 'EMP181', 'Empréstimo',         'gasto', '💳', '#059669', TRUE),
    (182, 'CAR182', 'Cartão Crédito',     'gasto', '💳', '#059669', TRUE),
    (183, 'TAR183', 'Tarifas Bancárias',  'gasto', '🏦', '#059669', TRUE),
    (184, 'SEG184', 'Seguro',             'gasto', '🛡️', '#059669', TRUE);

-- Reseta a sequência para continuar após o maior ID inserido (195)
SELECT setval(pg_get_serial_sequence('categorias','id_categorias'), 195);


-- ═══════════════════════════════════════════════════════════════
--  SEED — CATEGORIAS_PAI (hierarquia pai/filho)
-- ═══════════════════════════════════════════════════════════════
INSERT INTO categorias_pai (categoria_id, categoria_code, pai_id, pai_code) VALUES
    -- Alimentação
    (101,'SUP101', 10,'ALI010'), (102,'RES102', 10,'ALI010'),
    (103,'DEL103', 10,'ALI010'), (104,'PAD104', 10,'ALI010'),
    (105,'LAN105', 10,'ALI010'),
    -- Transporte
    (111,'COM111', 11,'TRA011'), (112,'UBE112', 11,'TRA011'),
    (113,'TPU113', 11,'TRA011'), (114,'EST114', 11,'TRA011'),
    (115,'MAN115', 11,'TRA011'),
    -- Moradia
    (121,'ALU121', 12,'MOR012'), (122,'CON122', 12,'MOR012'),
    (123,'ENE123', 12,'MOR012'), (124,'AGU124', 12,'MOR012'),
    (125,'WEB125', 12,'MOR012'), (126,'GAS126', 12,'MOR012'),
    -- Saúde
    (131,'PLS131', 13,'SAU013'), (132,'FAR132', 13,'SAU013'),
    (133,'MED133', 13,'SAU013'), (134,'ACA134', 13,'SAU013'),
    -- Educação
    (141,'MEN141', 14,'EDU014'), (142,'CUR142', 14,'EDU014'),
    (143,'LIV143', 14,'EDU014'),
    -- Lazer
    (151,'CIN151', 15,'LAZ015'), (152,'JOG152', 15,'LAZ015'),
    (153,'VIA153', 15,'LAZ015'), (154,'BAR154', 15,'LAZ015'),
    -- Assinaturas
    (171,'CEL171', 17,'ASS017'), (172,'SOF172', 17,'ASS017'),
    (173,'CLU173', 17,'ASS017'),
    -- Streaming
    (191,'NET191', 19,'STR019'), (192,'SPO192', 19,'STR019'),
    (193,'YOU193', 19,'STR019'), (194,'DIS194', 19,'STR019'),
    (195,'AMA195', 19,'STR019'),
    -- Financeiro
    (181,'EMP181', 18,'FIN018'), (182,'CAR182', 18,'FIN018'),
    (183,'TAR183', 18,'FIN018'), (184,'SEG184', 18,'FIN018');


-- ═══════════════════════════════════════════════════════════════
--  SEED — CATEGORIA_THRESHOLDS
--  Streaming=90, Alimentação/Delivery=70, Outros=100 (nunca auto)
-- ═══════════════════════════════════════════════════════════════
INSERT INTO categoria_thresholds (categoria_id, categoria_code, threshold_auto, threshold_alerta, ambiguidade_alta) VALUES
    (19,  'STR019', 90,  50, FALSE),   -- Streaming
    (103, 'DEL103', 70,  50, FALSE),   -- Delivery
    (10,  'ALI010', 70,  50, FALSE),   -- Alimentação
    (20,  'OUT020', 100, 50, TRUE);    -- Outros (nunca auto)


-- ═══════════════════════════════════════════════════════════════
--  SEED — MOTIVOS_CANCELAMENTO
-- ═══════════════════════════════════════════════════════════════
INSERT INTO motivos_cancelamento
    (id_motivos_cancelamento, motivos_cancelamento_code, descricao, origem_permitida, ativo)
VALUES
    (1, 'MOT001', 'Lançamento duplicado',                    'todos',    TRUE),
    (2, 'MOT002', 'Erro de valor informado',                 'usuario',  TRUE),
    (3, 'MOT003', 'Transação não reconhecida pelo usuário',  'usuario',  TRUE),
    (4, 'MOT004', 'Estorno realizado pelo estabelecimento',  'sistema',  TRUE),
    (5, 'MOT005', 'Cancelado pelo usuário',                  'usuario',  TRUE),
    (6, 'MOT006', 'Cancelado automaticamente pelo sistema',  'sistema',  TRUE),
    (7, 'MOT007', 'Cancelado por revisão administrativa',    'admin',    TRUE),
    (8, 'MOT008', 'Arquivo de extrato reprocessado',         'sistema',  TRUE);

SELECT setval(pg_get_serial_sequence('motivos_cancelamento','id_motivos_cancelamento'), 8);


-- ═══════════════════════════════════════════════════════════════
--  SEED — USUÁRIO DE DEMONSTRAÇÃO + dados relacionados
-- ═══════════════════════════════════════════════════════════════
-- ATENÇÃO:
--   • senha_hash é placeholder bcrypt — substitua via API em produção
--   • CPF é fictício sem criptografia real — use AES-256 na aplicação

DO $$
DECLARE
  -- usuário
  v_usr_id    BIGINT;  v_usr_code    VARCHAR(6);

  -- contas
  v_nub_id    BIGINT;  v_nub_code    VARCHAR(6);
  v_ita_id    BIGINT;  v_ita_code    VARCHAR(6);
  v_car_id    BIGINT;  v_car_code    VARCHAR(6);

  -- extrato
  v_ext_id    BIGINT;  v_ext_code    VARCHAR(6);

  -- parser
  v_par_id    BIGINT;  v_par_code    VARCHAR(6);

  -- transação amazon (será cancelada)
  v_amz_id    BIGINT;  v_amz_code    VARCHAR(6);
  v_amz_val   NUMERIC(15,2) := 215.00;

  -- motivo cancelamento
  v_mot_id    BIGINT;  v_mot_code    VARCHAR(6);

  v_corr      BIGINT;

BEGIN

  -- ── Parser Nubank ─────────────────────────────────────────
  -- Gera o correlation_id para rastrear todo este fluxo de seed
  v_corr := nextval('correlation_id_seq');

  SELECT id_parser_versoes, parser_versoes_code
    INTO v_par_id, v_par_code
    FROM parser_versoes WHERE banco = 'Nubank' AND versao = 'v1.0';

  -- ── Motivo cancelamento (Cancelado pelo usuário) ───────────
  SELECT id_motivos_cancelamento, motivos_cancelamento_code
    INTO v_mot_id, v_mot_code
    FROM motivos_cancelamento WHERE id_motivos_cancelamento = 5;

  -- ── Usuário ───────────────────────────────────────────────
  INSERT INTO usuarios (
    codigo, cpf, cpf_hash, nome_completo, email, senha_hash,
    telefone, saldo_inicial_definido, moeda, ativo, email_verificado,
    ultimo_login, versao
  ) VALUES (
    'FIN-DEMO01',
    'ENCRYPTED_CPF_PLACEHOLDER',
    encode(sha256('12345678909'::bytea), 'hex'),
    'João Silva Demonstração',
    'joao.demo@finapp.com.br',
    '$2b$12$K2hXdW7eL9mNqRvP3sBuCeXgTlAaDz5yQfJcMkwE1nHoVpYrI8uGa',
    '(11) 99999-0000',
    TRUE, 'BRL', TRUE, TRUE,
    NOW(), 1
  )
  RETURNING id_usuarios, usuarios_code INTO v_usr_id, v_usr_code;

  -- ── Consentimentos LGPD ───────────────────────────────────
  INSERT INTO consentimentos_lgpd
    (usuario_id, usuario_code, tipo, versao_politica, consentido, ip_origem)
  VALUES
    (v_usr_id, v_usr_code, 'tratamento_dados_financeiros', '1.0', TRUE, '192.0.2.1'),
    (v_usr_id, v_usr_code, 'uso_ia',                       '1.0', TRUE, '192.0.2.1'),
    (v_usr_id, v_usr_code, 'armazenamento_extrato',        '1.0', TRUE, '192.0.2.1');

  -- ── Contas financeiras ────────────────────────────────────
  INSERT INTO contas_financeiras
    (usuario_id, usuario_code, nome, tipo, banco, saldo_inicial, padrao, ativa)
  VALUES
    (v_usr_id, v_usr_code, 'Nubank Conta',     'corrente', 'Nubank', 2500.00, TRUE,  TRUE)
  RETURNING id_contas_financeiras, contas_financeiras_code INTO v_nub_id, v_nub_code;

  INSERT INTO contas_financeiras
    (usuario_id, usuario_code, nome, tipo, banco, saldo_inicial, padrao, ativa)
  VALUES
    (v_usr_id, v_usr_code, 'Itaú Corrente',   'corrente', 'Itaú',  10000.00, FALSE, TRUE)
  RETURNING id_contas_financeiras, contas_financeiras_code INTO v_ita_id, v_ita_code;

  INSERT INTO contas_financeiras
    (usuario_id, usuario_code, nome, tipo, banco, saldo_inicial, padrao, ativa)
  VALUES
    (v_usr_id, v_usr_code, 'Carteira/Dinheiro','dinheiro', NULL,     300.00, FALSE, TRUE)
  RETURNING id_contas_financeiras, contas_financeiras_code INTO v_car_id, v_car_code;

  -- ── Categorias do usuário (vincula categorias globais ao usuário) ─
  INSERT INTO categorias_do_usuario (usuario_id, usuario_code, categoria_id, categoria_code)
  VALUES
    (v_usr_id, v_usr_code,   1, 'SAL001'),   -- Salário
    (v_usr_id, v_usr_code,   2, 'FRE002'),   -- Freelance
    (v_usr_id, v_usr_code,  10, 'ALI010'),   -- Alimentação
    (v_usr_id, v_usr_code,  11, 'TRA011'),   -- Transporte
    (v_usr_id, v_usr_code,  12, 'MOR012'),   -- Moradia
    (v_usr_id, v_usr_code,  13, 'SAU013'),   -- Saúde
    (v_usr_id, v_usr_code,  19, 'STR019'),   -- Streaming
    (v_usr_id, v_usr_code,  20, 'OUT020'),   -- Outros
    (v_usr_id, v_usr_code, 101, 'SUP101'),   -- Supermercado
    (v_usr_id, v_usr_code, 103, 'DEL103'),   -- Delivery
    (v_usr_id, v_usr_code, 112, 'UBE112'),   -- Uber/99
    (v_usr_id, v_usr_code, 123, 'ENE123'),   -- Energia
    (v_usr_id, v_usr_code, 132, 'FAR132'),   -- Farmácia
    (v_usr_id, v_usr_code, 105, 'LAN105'),   -- Lanchonete
    (v_usr_id, v_usr_code, 191, 'NET191');   -- Netflix

  -- ── Extrato (Nubank — Maio 2025) ──────────────────────────
  INSERT INTO extratos (
    usuario_id, usuario_code, conta_id, conta_code,
    arquivo_nome, arquivo_uuid, hash_arquivo,
    banco_detectado, parser_versao_id, parser_versao_code,
    score_extracao, periodo_inicio, periodo_fim, status,
    total_lancamentos, lancamentos_confirmados, lancamentos_pendentes
  ) VALUES (
    v_usr_id, v_usr_code, v_nub_id, v_nub_code,
    'nubank_maio_2025.pdf',
    gen_random_uuid()::text,
    encode(sha256('nubank_maio_2025_content_hash'::bytea), 'hex'),
    'Nubank', v_par_id, v_par_code,
    0.980, '2025-05-01', '2025-05-31', 'concluido',
    8, 6, 2
  )
  RETURNING id_extratos, extratos_code INTO v_ext_id, v_ext_code;

  -- ── Transações — Gastos (via extrato PDF) ─────────────────
  INSERT INTO transacoes (
    usuario_id, usuario_code, conta_id, conta_code,
    extrato_id, extrato_code, tipo,
    descricao_original, descricao_normalizada,
    valor, data_transacao, categoria_id, categoria_code,
    subcategoria, estabelecimento, origem, status_revisao, confianca_ia
  ) VALUES
    -- Supermercado
    (v_usr_id, v_usr_code, v_nub_id, v_nub_code,
     v_ext_id, v_ext_code, 'gasto',
     'COMPRA 02/05 PAGUE MENOS SP', 'COMPRA PAGUE MENOS SP',
     347.89, '2025-05-02', 101, 'SUP101',
     'Supermercado', 'Pague Menos', 'pdf', 'confirmada', 92),

    -- Delivery
    (v_usr_id, v_usr_code, v_nub_id, v_nub_code,
     v_ext_id, v_ext_code, 'gasto',
     'COMPRA 04/05 IFOOD*RESTAURANTE SP', 'IFOOD RESTAURANTE SP',
     58.90, '2025-05-04', 103, 'DEL103',
     'Delivery', 'iFood', 'pdf', 'confirmada', 95),

    -- Uber
    (v_usr_id, v_usr_code, v_nub_id, v_nub_code,
     v_ext_id, v_ext_code, 'gasto',
     'COMPRA 05/05 UBER *TRIP SP', 'UBER TRIP SP',
     34.70, '2025-05-05', 112, 'UBE112',
     'Uber/99', 'Uber', 'pdf', 'confirmada', 98),

    -- Netflix
    (v_usr_id, v_usr_code, v_nub_id, v_nub_code,
     v_ext_id, v_ext_code, 'gasto',
     'COMPRA 07/05 NETFLIX.COM SP', 'NETFLIX COM SP',
     55.90, '2025-05-07', 191, 'NET191',
     'Streaming', 'Netflix', 'pdf', 'confirmada', 99),

    -- Farmácia
    (v_usr_id, v_usr_code, v_nub_id, v_nub_code,
     v_ext_id, v_ext_code, 'gasto',
     'COMPRA 10/05 DROGA RAIA SP', 'DROGA RAIA SP',
     89.50, '2025-05-10', 132, 'FAR132',
     'Farmácia', 'Droga Raia', 'pdf', 'confirmada', 91);

  -- ── Transações — Gastos (lançamentos manuais) ─────────────
  INSERT INTO transacoes (
    usuario_id, usuario_code, conta_id, conta_code,
    tipo, descricao_normalizada, valor, data_transacao,
    categoria_id, categoria_code, subcategoria, estabelecimento,
    origem, status_revisao
  ) VALUES
    -- Conta de luz (Itaú)
    (v_usr_id, v_usr_code, v_ita_id, v_ita_code,
     'gasto', 'ENEL SP ENERGIA ELETRICA',
     180.00, '2025-05-12', 123, 'ENE123',
     'Energia', 'ENEL SP', 'manual', 'confirmada'),

    -- Lanchonete (carteira)
    (v_usr_id, v_usr_code, v_car_id, v_car_code,
     'gasto', 'LANCHONETE ESQUINA',
     22.00, '2025-05-22', 105, 'LAN105',
     'Lanchonete', 'Lanchonete Esquina', 'manual', 'confirmada');

  -- ── Transação Amazon (será cancelada a seguir) ────────────
  INSERT INTO transacoes (
    usuario_id, usuario_code, conta_id, conta_code,
    extrato_id, extrato_code, tipo,
    descricao_original, descricao_normalizada,
    valor, data_transacao, categoria_id, categoria_code,
    estabelecimento, origem, status_revisao, confianca_ia
  ) VALUES (
    v_usr_id, v_usr_code, v_nub_id, v_nub_code,
    v_ext_id, v_ext_code, 'gasto',
    'COMPRA 20/05 AMAZON MKTPLC SP', 'AMAZON MKTPLC SP',
    v_amz_val, '2025-05-20', 20, 'OUT020',
    'Amazon', 'pdf', 'pendente_revisao', 45
  )
  RETURNING id_transacoes, transacoes_code INTO v_amz_id, v_amz_code;

  -- ── Cancela a transação Amazon ────────────────────────────
  -- 1) soft delete na transação original
  UPDATE transacoes
     SET deleted_at     = NOW(),
         status_revisao = 'arquivada',
         atualizado_em  = NOW()
   WHERE id_transacoes = v_amz_id;

  -- 2) registra o cancelamento com rastreabilidade completa
  INSERT INTO transacoes_canceladas (
    transacao_id, transacao_code,
    usuario_id, usuario_code,
    conta_id, conta_code,
    motivo_id, motivo_code,
    cancelado_por, valor_original, observacao, ip_origem
  ) VALUES (
    v_amz_id, v_amz_code,
    v_usr_id, v_usr_code,
    v_nub_id, v_nub_code,
    v_mot_id, v_mot_code,
    'usuario', v_amz_val,
    'Compra não reconhecida pelo usuário — possível fraude',
    '192.0.2.1'
  );

  -- ── Transações — Receitas ─────────────────────────────────
  INSERT INTO transacoes (
    usuario_id, usuario_code, conta_id, conta_code,
    tipo, descricao_usuario, descricao_normalizada,
    valor, data_transacao, categoria_id, categoria_code,
    subcategoria, origem, status_revisao, recorrente, periodo_recorrencia
  ) VALUES
    -- Salário
    (v_usr_id, v_usr_code, v_ita_id, v_ita_code,
     'receita', 'Salário Maio/2025', 'SALARIO MAIO 2025',
     6800.00, '2025-05-05', 1, 'SAL001',
     NULL, 'manual', 'confirmada', TRUE, 'mensal'),

    -- Freelance
    (v_usr_id, v_usr_code, v_nub_id, v_nub_code,
     'receita', 'Projeto Web — Cliente ABC', 'PROJETO WEB CLIENTE ABC',
     1500.00, '2025-05-15', 2, 'FRE002',
     'Desenvolvimento', 'manual', 'confirmada', FALSE, NULL);

  -- ── Snapshot financeiro Maio 2025 ─────────────────────────
  -- Conta Nubank (não inclui o valor da Amazon que foi cancelada)
  INSERT INTO snapshots_financeiros (
    usuario_id, usuario_code, conta_id, conta_code,
    ano, mes, saldo_inicial, total_receitas, total_gastos, saldo_final
  ) VALUES
    (v_usr_id, v_usr_code, v_nub_id, v_nub_code,
     2025, 5,
     2500.00,
     1500.00,
     (347.89 + 58.90 + 34.70 + 55.90 + 89.50),  -- Amazon excluída (cancelada)
     2500.00 + 1500.00 - (347.89 + 58.90 + 34.70 + 55.90 + 89.50)),

    -- Conta Itaú
    (v_usr_id, v_usr_code, v_ita_id, v_ita_code,
     2025, 5,
     10000.00,
     6800.00,
     180.00,
     10000.00 + 6800.00 - 180.00),

    -- Consolidado
    (v_usr_id, v_usr_code, NULL, NULL,
     2025, 5,
     12800.00,
     (6800.00 + 1500.00),
     (347.89 + 58.90 + 34.70 + 55.90 + 89.50 + 180.00 + 22.00),
     12800.00 + 8300.00 - (347.89 + 58.90 + 34.70 + 55.90 + 89.50 + 180.00 + 22.00));

  -- ── Auditoria: criação do usuário ─────────────────────────
  INSERT INTO auditoria_eventos (
    correlation_id, usuario_id, usuario_code,
    entidade, entidade_id, acao,
    dados_novos, ip_origem, origem
  ) VALUES (
    v_corr, v_usr_id, v_usr_code,
    'usuario', v_usr_id, 'CREATE',
    '{"nome_completo":"João Silva Demonstração","email":"joao.demo@finapp.com.br","moeda":"BRL"}'::jsonb,
    '192.0.2.1', 'web'
  );

  -- ── Auditoria: cancelamento da transação Amazon ───────────
  -- Reutiliza o mesmo v_corr para encadear os dois eventos no mesmo fluxo
  INSERT INTO auditoria_eventos (
    correlation_id, usuario_id, usuario_code,
    entidade, entidade_id, acao,
    dados_anteriores, dados_novos, ip_origem, origem
  ) VALUES (
    v_corr, v_usr_id, v_usr_code,
    'transacao', v_amz_id, 'CANCEL',
    jsonb_build_object('status_revisao','pendente_revisao','valor', v_amz_val),
    jsonb_build_object('status_revisao','arquivada','cancelado_por','usuario'),
    '192.0.2.1', 'web'
  );

  -- ── Notificação de boas-vindas ────────────────────────────
  INSERT INTO notificacoes
    (usuario_id, usuario_code, canal, tipo, titulo, mensagem, enviada, enviada_em)
  VALUES (
    v_usr_id, v_usr_code,
    'email', 'boas_vindas',
    'Bem-vindo ao FinApp! 🎉',
    'Olá João, sua conta foi criada com sucesso. Comece importando seu primeiro extrato!',
    TRUE, NOW()
  );

END $$;


-- ═══════════════════════════════════════════════════════════════
--  VERIFICAÇÃO RÁPIDA (descomente para executar)
-- ═══════════════════════════════════════════════════════════════
/*
SELECT tabela, total FROM (
  SELECT 'usuarios'                 AS tabela, COUNT(*) AS total FROM usuarios
  UNION ALL SELECT 'contas_financeiras',        COUNT(*) FROM contas_financeiras
  UNION ALL SELECT 'categorias',                COUNT(*) FROM categorias
  UNION ALL SELECT 'categorias_pai',            COUNT(*) FROM categorias_pai
  UNION ALL SELECT 'categorias_do_usuario',     COUNT(*) FROM categorias_do_usuario
  UNION ALL SELECT 'categoria_thresholds',      COUNT(*) FROM categoria_thresholds
  UNION ALL SELECT 'motivos_cancelamento',      COUNT(*) FROM motivos_cancelamento
  UNION ALL SELECT 'extratos',                  COUNT(*) FROM extratos
  UNION ALL SELECT 'transacoes',                COUNT(*) FROM transacoes
  UNION ALL SELECT 'transacoes_canceladas',     COUNT(*) FROM transacoes_canceladas
  UNION ALL SELECT 'snapshots_financeiros',     COUNT(*) FROM snapshots_financeiros
  UNION ALL SELECT 'auditoria_eventos',         COUNT(*) FROM auditoria_eventos
  UNION ALL SELECT 'consentimentos_lgpd',       COUNT(*) FROM consentimentos_lgpd
  UNION ALL SELECT 'notificacoes',              COUNT(*) FROM notificacoes
  UNION ALL SELECT 'parser_versoes',            COUNT(*) FROM parser_versoes
) t ORDER BY tabela;
*/
