-- ============================================================
--  FINAPP — Script de criação do banco de dados
--  Curado manualmente a partir do mapeamento JPA atual (adapters/out/persistence/**)
--  PostgreSQL 14+
--  Atualizado em: 2026-07-13
--
--  Convenção adotada em todas as tabelas:
--    - PK própria:   <entidade>_id   BIGINT GENERATED BY DEFAULT AS IDENTITY
--    - Código único: <entidade>_code VARCHAR(6) NOT NULL UNIQUE
--    - Toda referência de FK usa o PAR (xxx_id, xxx_code) — chave composta.
-- ============================================================

-- ─────────────────────────────────────────────
--  EXTENSÕES
-- ─────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ═══════════════════════════════════════════════════════════════
--  TABELAS REMOVIDAS NESTA REVISÃO
--  As tabelas abaixo existiam em revisões anteriores deste script mas
--  NÃO correspondem a nenhuma entidade JPA atual do backend
--  (adapters/out/persistence/**). Prováveis resíduos de uma iteração
--  anterior do app. Removidas aqui; se ainda existirem dados em produção,
--  avalie migração/backup antes de aplicar este script em cima de um banco
--  existente:
--    - categorias_do_usuario
--    - categorias_pai
--    - gastos
-- ═══════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════
--  TABELAS
--  Ordem respeita dependências de FK
-- ═══════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────
--  USUARIOS  (sem FK)
-- ─────────────────────────────────────────────
CREATE TABLE usuarios (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_code VARCHAR(6) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(255),
    telegram_chatid BIGINT,
    whatsapp_chatid BIGINT,
    email_verificado BOOLEAN,
    dt_nascimento DATE NOT NULL,
    PRIMARY KEY (usuario_id)
);

-- ─────────────────────────────────────────────
--  BANCO  (catálogo de instituições financeiras — sem FK)
-- ─────────────────────────────────────────────
CREATE TABLE banco (
    banco_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    banco_code VARCHAR(6) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    cor_hex VARCHAR(7),
    icone VARCHAR(50),
    PRIMARY KEY (banco_id)
);

-- ─────────────────────────────────────────────
--  CATEGORIAS  (sem FK)
-- ─────────────────────────────────────────────
CREATE TABLE categorias (
    categoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    categoria_code VARCHAR(6) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('RECEITA','GASTO','AMBOS')),
    icone VARCHAR(50),
    cor_hex VARCHAR(7),
    padrao BOOLEAN,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (categoria_id)
);

-- ─────────────────────────────────────────────
--  CATEGORIA_THRESHOLDS  → FK composta para categorias
-- ─────────────────────────────────────────────
CREATE TABLE categoria_thresholds (
    categoria_threshold_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    categoria_threshold_code VARCHAR(6) NOT NULL,
    categoria_id BIGINT NOT NULL,
    categoria_code VARCHAR(6) NOT NULL,
    threshold_auto SMALLINT NOT NULL DEFAULT 70,
    threshold_alerta SMALLINT NOT NULL DEFAULT 50,
    ambiguidade_alta BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (categoria_threshold_id)
);

-- ─────────────────────────────────────────────
--  MOTIVOS_CANCELAMENTO  (sem FK)
-- ─────────────────────────────────────────────
CREATE TABLE motivos_cancelamento (
    motivo_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    motivo_code VARCHAR(6) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    origem_permitida VARCHAR(20) NOT NULL DEFAULT 'todos'
        CHECK (origem_permitida IN ('usuario','sistema','admin','todos')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (motivo_id)
);

-- ─────────────────────────────────────────────
--  CONTAS_FINANCEIRAS  → FK composta para usuarios e banco
-- ─────────────────────────────────────────────
CREATE TABLE contas_financeiras (
    conta_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    conta_code VARCHAR(6) NOT NULL,
    usuario_id BIGINT NOT NULL,
    usuario_code VARCHAR(6) NOT NULL,
    banco_id BIGINT NOT NULL,
    banco_code VARCHAR(6) NOT NULL,
    tipo VARCHAR(20) NOT NULL
        CHECK (tipo IN ('corrente','poupanca','cartao','dinheiro','investimento')),
    saldo_inicial NUMERIC(15,2) NOT NULL DEFAULT 0,
    saldo_atual NUMERIC(15,2) NOT NULL DEFAULT 0,
    saldo_economias NUMERIC(15,2) NOT NULL DEFAULT 0,
    padrao BOOLEAN DEFAULT FALSE,
    ativa BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE,
    ind_delete VARCHAR(1) NOT NULL DEFAULT 'N',
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (conta_id)
);

-- ─────────────────────────────────────────────
--  TRANSACOES  → FK composta para contas_financeiras e categorias
--  Mantém o prefixo "transacoes_" no id/code (nome já usado por
--  ContaFinanceiraEntity/TransacaoEntity como referência do refactor).
-- ─────────────────────────────────────────────
CREATE TABLE transacoes (
    transacoes_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transacoes_code VARCHAR(6) NOT NULL,
    conta_id BIGINT NOT NULL,
    conta_code VARCHAR(6) NOT NULL,
    ind_estorno VARCHAR(1) NOT NULL DEFAULT 'N',
    descricao TEXT,
    valor NUMERIC(15,2) NOT NULL,
    data_transacao DATE NOT NULL,
    categoria_id BIGINT NOT NULL,
    categoria_code VARCHAR(6) NOT NULL,
    estabelecimento VARCHAR(255),
    origem VARCHAR(20) NOT NULL DEFAULT 'manual'
        CHECK (origem IN ('manual','pdf','api')),
    status_revisao VARCHAR(30) NOT NULL DEFAULT 'EXTRAIDA'
        CHECK (status_revisao IN (
            'EXTRAIDA','CLASSIFICADA','PENDENTE_REVISAO',
            'CONFIRMADA','IGNORADA','ARQUIVADA'
        )),
    confianca_ia SMALLINT,
    recorrente BOOLEAN DEFAULT FALSE,
    periodo_recorrencia DATE,
    observacao TEXT,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    estornado_at TIMESTAMP(6) WITH TIME ZONE,
    versao INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE,
    transacao_estornada_id BIGINT,
    PRIMARY KEY (transacoes_id)
);

-- ─────────────────────────────────────────────
--  TRANSACOES_CANCELADAS  → FK composta para transacoes e motivos_cancelamento
-- ─────────────────────────────────────────────
CREATE TABLE transacoes_canceladas (
    transacao_cancelada_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transacao_cancelada_code VARCHAR(6) NOT NULL,
    transacao_id BIGINT NOT NULL,
    transacao_code VARCHAR(6) NOT NULL,
    motivo_id BIGINT NOT NULL,
    motivo_code VARCHAR(6) NOT NULL,
    cancelado_por VARCHAR(20) NOT NULL DEFAULT 'usuario'
        CHECK (cancelado_por IN ('usuario','sistema','admin')),
    valor_original NUMERIC(15,2) NOT NULL,
    observacao TEXT,
    ip_origem VARCHAR(45),
    cancelado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (transacao_cancelada_id)
);

-- ─────────────────────────────────────────────
--  MOVIMENTACOES_ECONOMIA  → FK composta para contas_financeiras
--  Ledger de auditoria dos aportes/resgates do sub-saldo "Economias"
--  (parte de contas_financeiras.saldo_economias). NÃO é receita nem gasto:
--  é uma transferência interna dentro da MESMA conta e por isso NÃO usa
--  a tabela transacoes (que assume tipo RECEITA/GASTO por categoria).
-- ─────────────────────────────────────────────
CREATE TABLE movimentacoes_economia (
    movimentacao_economia_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movimentacao_economia_code VARCHAR(6) NOT NULL,
    conta_id BIGINT NOT NULL,
    conta_code VARCHAR(6) NOT NULL,
    tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('APORTE','RESGATE')),
    valor NUMERIC(15,2) NOT NULL,
    descricao TEXT,
    data_movimentacao TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (movimentacao_economia_id)
);

-- ─────────────────────────────────────────────
--  PARSER_VERSOES  (sem FK)
-- ─────────────────────────────────────────────
CREATE TABLE parser_versoes (
    parser_versao_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parser_versao_code VARCHAR(6) NOT NULL,
    banco VARCHAR(100) NOT NULL,
    versao VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    score_qualidade NUMERIC(4,3),
    total_usos INTEGER NOT NULL DEFAULT 0,
    total_erros INTEGER NOT NULL DEFAULT 0,
    descricao TEXT,
    depreciado_em TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (parser_versao_id)
);

-- ─────────────────────────────────────────────
--  EXTRATOS  → FK composta para usuarios, contas_financeiras,
--              transacoes (nullable) e parser_versoes (nullable)
-- ─────────────────────────────────────────────
CREATE TABLE extratos (
    extrato_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    extrato_code VARCHAR(6) NOT NULL,
    usuario_id BIGINT NOT NULL,
    usuario_code VARCHAR(6) NOT NULL,
    conta_id BIGINT NOT NULL,
    conta_code VARCHAR(6) NOT NULL,
    transacao_id BIGINT,
    transacao_code VARCHAR(6),
    arquivo_nome VARCHAR(255),
    arquivo_uuid VARCHAR(255) NOT NULL,
    hash_arquivo VARCHAR(64) NOT NULL,
    banco_detectado VARCHAR(100),
    parser_versao_id BIGINT,
    parser_versao_code VARCHAR(6),
    score_extracao NUMERIC(4,3),
    periodo_inicio DATE,
    periodo_fim DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'upload_recebido'
        CHECK (status IN (
            'upload_recebido','validando','na_fila','extraindo',
            'classificando','aguardando_ia','pendente_revisao',
            'parcialmente_revisado','concluido','erro_formato',
            'erro_extracao','erro_classificacao','erro_timeout',
            'cancelado','reprocessando'
        )),
    total_lancamentos INTEGER NOT NULL DEFAULT 0,
    lancamentos_confirmados INTEGER NOT NULL DEFAULT 0,
    lancamentos_pendentes INTEGER NOT NULL DEFAULT 0,
    lancamentos_ignorados INTEGER NOT NULL DEFAULT 0,
    versao INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE,
    ind_delete VARCHAR(1) NOT NULL DEFAULT 'N',
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (extrato_id)
);

-- ─────────────────────────────────────────────
--  PROCESSAMENTO_JOBS  → FK composta para extratos
-- ─────────────────────────────────────────────
CREATE TABLE processamento_jobs (
    processamento_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    processamento_job_code VARCHAR(6) NOT NULL,
    extrato_id BIGINT NOT NULL,
    extrato_code VARCHAR(6) NOT NULL,
    tipo VARCHAR(30) NOT NULL
        CHECK (tipo IN (
            'extracao_pdf','classificacao_ia','notificacao',
            'geracao_pdf','snapshot','anonimizacao'
        )),
    status VARCHAR(30) NOT NULL DEFAULT 'enfileirado'
        CHECK (status IN (
            'enfileirado','iniciando','processando','aguardando_ia',
            'concluido','falha_ia','falha_parser','timeout',
            'retry_1','retry_2','retry_3','dead_letter','cancelado'
        )),
    tentativas SMALLINT NOT NULL DEFAULT 0,
    max_tentativas SMALLINT NOT NULL DEFAULT 3,
    payload TEXT,
    erro_mensagem TEXT,
    worker_id VARCHAR(100),
    lock_expires_at TIMESTAMP(6) WITH TIME ZONE,
    correlation_id BIGINT,
    enfileirado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    iniciado_em TIMESTAMP(6) WITH TIME ZONE,
    concluido_em TIMESTAMP(6) WITH TIME ZONE,
    proximo_retry TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (processamento_job_id)
);

-- ─────────────────────────────────────────────
--  CONSENTIMENTOS_LGPD  → FK composta para usuarios
-- ─────────────────────────────────────────────
CREATE TABLE consentimentos_lgpd (
    consentimento_lgpd_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    consentimento_lgpd_code VARCHAR(6) NOT NULL,
    usuario_id BIGINT NOT NULL,
    usuario_code VARCHAR(6) NOT NULL,
    tipo VARCHAR(50) NOT NULL
        CHECK (tipo IN (
            'tratamento_dados_financeiros','uso_ia',
            'armazenamento_extrato','bot_whatsapp','bot_telegram'
        )),
    versao_politica VARCHAR(20) NOT NULL,
    consentido BOOLEAN NOT NULL,
    ip_origem VARCHAR(45),
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revogado_em TIMESTAMP(6) WITH TIME ZONE,
    revogado_motivo TEXT,
    PRIMARY KEY (consentimento_lgpd_id)
);

-- ─────────────────────────────────────────────
--  NOTIFICACOES  → FK composta para usuarios
-- ─────────────────────────────────────────────
CREATE TABLE notificacoes (
    notificacao_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    notificacao_code VARCHAR(6) NOT NULL,
    usuario_id BIGINT NOT NULL,
    usuario_code VARCHAR(6) NOT NULL,
    canal VARCHAR(20) NOT NULL CHECK (canal IN ('whatsapp','telegram','email')),
    tipo VARCHAR(50) NOT NULL,
    titulo VARCHAR(255),
    mensagem TEXT,
    enviada BOOLEAN NOT NULL DEFAULT FALSE,
    enviada_em TIMESTAMP(6) WITH TIME ZONE,
    erro TEXT,
    tentativas SMALLINT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (notificacao_id)
);

-- ─────────────────────────────────────────────
--  SESSAO_TOKENS  (NOVA — não existia nas revisões anteriores deste
--  script; corresponde a SessaoTokenEntity, usada para sessão/login)
--  → FK composta para usuarios
-- ─────────────────────────────────────────────
CREATE TABLE sessao_tokens (
    sessao_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sessao_token_code VARCHAR(6) NOT NULL,
    token VARCHAR(255) NOT NULL,
    usuario_id BIGINT NOT NULL,
    usuario_code VARCHAR(6) NOT NULL,
    criado_em TIMESTAMP(6) NOT NULL,
    expira_em TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (sessao_token_id)
);

-- ─────────────────────────────────────────────
--  SNAPSHOTS_FINANCEIROS  → FK composta para usuarios e
--  contas_financeiras (nullable — NULL representa o consolidado do usuário)
-- ─────────────────────────────────────────────
CREATE TABLE snapshots_financeiros (
    snapshot_financeiro_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    snapshot_financeiro_code VARCHAR(6) NOT NULL,
    usuario_id BIGINT NOT NULL,
    usuario_code VARCHAR(6) NOT NULL,
    conta_id BIGINT,
    conta_code VARCHAR(6),
    ano SMALLINT NOT NULL,
    mes SMALLINT NOT NULL,
    saldo_inicial NUMERIC(15,2) NOT NULL,
    total_receitas NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_gastos NUMERIC(15,2) NOT NULL DEFAULT 0,
    saldo_final NUMERIC(15,2) NOT NULL,
    fechado BOOLEAN NOT NULL DEFAULT FALSE,
    fechado_em TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (snapshot_financeiro_id)
);

-- ─────────────────────────────────────────────
--  AUDITORIA_EVENTOS  → FK composta para usuarios (nullable — eventos
--  de sistema sem usuário associado); entidade_id é polimórfico
--  (aponta para PKs de tabelas diferentes conforme "entidade") e por
--  isso não tem FK física.
-- ─────────────────────────────────────────────
CREATE TABLE auditoria_eventos (
    auditoria_evento_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    auditoria_evento_code VARCHAR(6) NOT NULL,
    correlation_id BIGINT NOT NULL,
    usuario_id BIGINT,
    usuario_code VARCHAR(6),
    entidade VARCHAR(50) NOT NULL,
    entidade_id BIGINT NOT NULL,
    acao VARCHAR(30) NOT NULL
        CHECK (acao IN (
            'CREATE','UPDATE','DELETE','LOGIN','LOGOUT','UPLOAD',
            'CLASSIFY','CONFIRM','REJECT','EXPORT','REPROCESS',
            'API_KEY_GEN','PASSWORD_CHANGE','CANCEL'
        )),
    dados_anteriores TEXT,
    dados_novos TEXT,
    ip_origem VARCHAR(45),
    user_agent TEXT,
    origem VARCHAR(20)
        CHECK (origem IN ('web','bot_whatsapp','bot_telegram','api','sistema')),
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (auditoria_evento_id)
);


-- ═══════════════════════════════════════════════════════════════
--  UNIQUE CONSTRAINTS
--  code isolado (unicidade de negócio) + par (id, code) — este
--  último é exigido pelo Postgres para servir de alvo de FK composta.
-- ═══════════════════════════════════════════════════════════════

ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_cpf UNIQUE (cpf);
ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_email UNIQUE (email);
ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_code UNIQUE (usuario_code);
ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_id_code UNIQUE (usuario_id, usuario_code);

ALTER TABLE banco ADD CONSTRAINT uk_banco_code UNIQUE (banco_code);
ALTER TABLE banco ADD CONSTRAINT uk_banco_id_code UNIQUE (banco_id, banco_code);

ALTER TABLE categorias ADD CONSTRAINT uk_categorias_code UNIQUE (categoria_code);
ALTER TABLE categorias ADD CONSTRAINT uk_categorias_id_code UNIQUE (categoria_id, categoria_code);

ALTER TABLE categoria_thresholds ADD CONSTRAINT uk_categoria_thresholds_code UNIQUE (categoria_threshold_code);
ALTER TABLE categoria_thresholds ADD CONSTRAINT uk_categoria_thresholds_categoria UNIQUE (categoria_id);

ALTER TABLE motivos_cancelamento ADD CONSTRAINT uk_motivos_cancelamento_code UNIQUE (motivo_code);
ALTER TABLE motivos_cancelamento ADD CONSTRAINT uk_motivos_cancelamento_id_code UNIQUE (motivo_id, motivo_code);

ALTER TABLE contas_financeiras ADD CONSTRAINT uk_contas_financeiras_code UNIQUE (conta_code);
ALTER TABLE contas_financeiras ADD CONSTRAINT uk_contas_financeiras_id_code UNIQUE (conta_id, conta_code);

ALTER TABLE transacoes ADD CONSTRAINT uk_transacoes_code UNIQUE (transacoes_code);
ALTER TABLE transacoes ADD CONSTRAINT uk_transacoes_id_code UNIQUE (transacoes_id, transacoes_code);

ALTER TABLE transacoes_canceladas ADD CONSTRAINT uk_transacoes_canceladas_code UNIQUE (transacao_cancelada_code);

ALTER TABLE movimentacoes_economia ADD CONSTRAINT uk_movimentacoes_economia_code UNIQUE (movimentacao_economia_code);

ALTER TABLE parser_versoes ADD CONSTRAINT uk_parser_versoes_code UNIQUE (parser_versao_code);
ALTER TABLE parser_versoes ADD CONSTRAINT uk_parser_versoes_id_code UNIQUE (parser_versao_id, parser_versao_code);

ALTER TABLE extratos ADD CONSTRAINT uk_extratos_code UNIQUE (extrato_code);
ALTER TABLE extratos ADD CONSTRAINT uk_extratos_id_code UNIQUE (extrato_id, extrato_code);

ALTER TABLE processamento_jobs ADD CONSTRAINT uk_processamento_jobs_code UNIQUE (processamento_job_code);

ALTER TABLE consentimentos_lgpd ADD CONSTRAINT uk_consentimentos_lgpd_code UNIQUE (consentimento_lgpd_code);

ALTER TABLE notificacoes ADD CONSTRAINT uk_notificacoes_code UNIQUE (notificacao_code);

ALTER TABLE sessao_tokens ADD CONSTRAINT uk_sessao_tokens_token UNIQUE (token);
ALTER TABLE sessao_tokens ADD CONSTRAINT uk_sessao_tokens_code UNIQUE (sessao_token_code);

ALTER TABLE snapshots_financeiros ADD CONSTRAINT uk_snapshots_financeiros_code UNIQUE (snapshot_financeiro_code);

ALTER TABLE auditoria_eventos ADD CONSTRAINT uk_auditoria_eventos_code UNIQUE (auditoria_evento_code);


-- ═══════════════════════════════════════════════════════════════
--  FOREIGN KEYS  (todas compostas: par id + code, exceto onde indicado)
-- ═══════════════════════════════════════════════════════════════

ALTER TABLE categoria_thresholds
    ADD CONSTRAINT fk_categoria_thresholds_categoria
    FOREIGN KEY (categoria_id, categoria_code) REFERENCES categorias (categoria_id, categoria_code);

ALTER TABLE contas_financeiras
    ADD CONSTRAINT fk_contas_financeiras_usuario
    FOREIGN KEY (usuario_id, usuario_code) REFERENCES usuarios (usuario_id, usuario_code);

ALTER TABLE contas_financeiras
    ADD CONSTRAINT fk_contas_financeiras_banco
    FOREIGN KEY (banco_id, banco_code) REFERENCES banco (banco_id, banco_code);

ALTER TABLE transacoes
    ADD CONSTRAINT fk_transacoes_conta
    FOREIGN KEY (conta_id, conta_code) REFERENCES contas_financeiras (conta_id, conta_code);

ALTER TABLE transacoes
    ADD CONSTRAINT fk_transacoes_categoria
    FOREIGN KEY (categoria_id, categoria_code) REFERENCES categorias (categoria_id, categoria_code);

ALTER TABLE transacoes_canceladas
    ADD CONSTRAINT fk_transacoes_canceladas_transacao
    FOREIGN KEY (transacao_id, transacao_code) REFERENCES transacoes (transacoes_id, transacoes_code);

ALTER TABLE transacoes_canceladas
    ADD CONSTRAINT fk_transacoes_canceladas_motivo
    FOREIGN KEY (motivo_id, motivo_code) REFERENCES motivos_cancelamento (motivo_id, motivo_code);

ALTER TABLE movimentacoes_economia
    ADD CONSTRAINT fk_movimentacoes_economia_conta
    FOREIGN KEY (conta_id, conta_code) REFERENCES contas_financeiras (conta_id, conta_code);

ALTER TABLE extratos
    ADD CONSTRAINT fk_extratos_usuario
    FOREIGN KEY (usuario_id, usuario_code) REFERENCES usuarios (usuario_id, usuario_code);

ALTER TABLE extratos
    ADD CONSTRAINT fk_extratos_conta
    FOREIGN KEY (conta_id, conta_code) REFERENCES contas_financeiras (conta_id, conta_code);

ALTER TABLE extratos
    ADD CONSTRAINT fk_extratos_transacao
    FOREIGN KEY (transacao_id, transacao_code) REFERENCES transacoes (transacoes_id, transacoes_code);

ALTER TABLE extratos
    ADD CONSTRAINT fk_extratos_parser_versao
    FOREIGN KEY (parser_versao_id, parser_versao_code) REFERENCES parser_versoes (parser_versao_id, parser_versao_code);

ALTER TABLE processamento_jobs
    ADD CONSTRAINT fk_processamento_jobs_extrato
    FOREIGN KEY (extrato_id, extrato_code) REFERENCES extratos (extrato_id, extrato_code);

ALTER TABLE consentimentos_lgpd
    ADD CONSTRAINT fk_consentimentos_lgpd_usuario
    FOREIGN KEY (usuario_id, usuario_code) REFERENCES usuarios (usuario_id, usuario_code);

ALTER TABLE notificacoes
    ADD CONSTRAINT fk_notificacoes_usuario
    FOREIGN KEY (usuario_id, usuario_code) REFERENCES usuarios (usuario_id, usuario_code);

ALTER TABLE sessao_tokens
    ADD CONSTRAINT fk_sessao_tokens_usuario
    FOREIGN KEY (usuario_id, usuario_code) REFERENCES usuarios (usuario_id, usuario_code);

ALTER TABLE snapshots_financeiros
    ADD CONSTRAINT fk_snapshots_financeiros_usuario
    FOREIGN KEY (usuario_id, usuario_code) REFERENCES usuarios (usuario_id, usuario_code);

ALTER TABLE snapshots_financeiros
    ADD CONSTRAINT fk_snapshots_financeiros_conta
    FOREIGN KEY (conta_id, conta_code) REFERENCES contas_financeiras (conta_id, conta_code);

-- auditoria_eventos.usuario_id/usuario_code: FK opcional (eventos de sistema
-- podem não ter usuário). entidade_id é polimórfico e não tem FK física.
ALTER TABLE auditoria_eventos
    ADD CONSTRAINT fk_auditoria_eventos_usuario
    FOREIGN KEY (usuario_id, usuario_code) REFERENCES usuarios (usuario_id, usuario_code);
