-- ============================================================
--  FINAPP — Script de criação do banco de dados
--  Extraído do log do Hibernate (ddl-auto)
--  PostgreSQL 14+
--  Gerado em: 2026-05-23
-- ============================================================

-- ─────────────────────────────────────────────
--  EXTENSÕES
-- ─────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ═══════════════════════════════════════════════════════════════
--  TABELAS
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE auditoria_eventos (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    acao             VARCHAR(30)  NOT NULL
                         CHECK (acao IN (
                             'CREATE','UPDATE','DELETE','LOGIN','LOGOUT','UPLOAD',
                             'CLASSIFY','CONFIRM','REJECT','EXPORT','REPROCESS',
                             'API_KEY_GEN','PASSWORD_CHANGE','CANCEL'
                         )),
    correlation_id   BIGINT       NOT NULL,
    criado_em        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    dados_anteriores TEXT,
    dados_novos      TEXT,
    entidade         VARCHAR(50)  NOT NULL,
    entidade_id      BIGINT       NOT NULL,
    ip_origem        VARCHAR(45),
    origem           VARCHAR(20)
                         CHECK (origem IN (
                             'web','bot_whatsapp','bot_telegram','api','sistema'
                         )),
    user_agent       TEXT,
    usuario_id       BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE categoria_thresholds (
    id               BIGINT    GENERATED BY DEFAULT AS IDENTITY,
    ambiguidade_alta BOOLEAN   NOT NULL,
    categoria_id     BIGINT    NOT NULL,
    threshold_alerta SMALLINT  NOT NULL,
    threshold_auto   SMALLINT  NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE categorias (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    categorias_code VARCHAR(6)   NOT NULL,
    cor_hex         VARCHAR(7),
    criado_em       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    icone           VARCHAR(50),
    nome            VARCHAR(100) NOT NULL,
    padrao          BOOLEAN,
    tipo            VARCHAR(10)  NOT NULL
                        CHECK (tipo IN ('receita','gasto','ambos')),
    PRIMARY KEY (id)
);

CREATE TABLE categorias_do_usuario (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    ativa        BOOLEAN      NOT NULL,
    categoria_id BIGINT       NOT NULL,
    criado_em    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    usuario_id   BIGINT       NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE categorias_pai (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    categoria_id BIGINT       NOT NULL,
    criado_em    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    pai_id       BIGINT       NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE consentimentos_lgpd (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    consentido      BOOLEAN      NOT NULL,
    criado_em       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ip_origem       VARCHAR(45),
    revogado_em     TIMESTAMP(6) WITH TIME ZONE,
    revogado_motivo TEXT,
    tipo            VARCHAR(50)  NOT NULL
                        CHECK (tipo IN (
                            'tratamento_dados_financeiros','uso_ia',
                            'armazenamento_extrato','bot_whatsapp','bot_telegram'
                        )),
    usuario_id      BIGINT       NOT NULL,
    versao_politica VARCHAR(20)  NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE contas_financeiras (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    ativa         BOOLEAN,
    atualizado_em TIMESTAMP(6)  WITH TIME ZONE,
    banco         VARCHAR(100),
    contas_code   VARCHAR(6)    NOT NULL,
    criado_em     TIMESTAMP(6)  WITH TIME ZONE NOT NULL,
    nome          VARCHAR(100)  NOT NULL,
    padrao        BOOLEAN,
    saldo_inicial NUMERIC(15,2) NOT NULL,
    tipo          VARCHAR(20)   NOT NULL
                      CHECK (tipo IN (
                          'corrente','poupanca','cartao','dinheiro','investimento'
                      )),
    usuario_id    BIGINT        NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE extratos (
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    arquivo_nome            VARCHAR(255),
    arquivo_uuid            VARCHAR(255)  NOT NULL,
    atualizado_em           TIMESTAMP(6)  WITH TIME ZONE,
    banco_detectado         VARCHAR(100),
    extratos_code           VARCHAR(6)    NOT NULL,
    conta_id                BIGINT        NOT NULL,
    criado_em               TIMESTAMP(6)  WITH TIME ZONE NOT NULL,
    hash_arquivo            VARCHAR(64)   NOT NULL,
    lancamentos_confirmados INTEGER       NOT NULL,
    lancamentos_ignorados   INTEGER       NOT NULL,
    lancamentos_pendentes   INTEGER       NOT NULL,
    parser_versao_id        BIGINT,
    periodo_fim             DATE,
    periodo_inicio          DATE,
    score_extracao          NUMERIC(4,3),
    status                  VARCHAR(30)   NOT NULL
                                CHECK (status IN (
                                    'upload_recebido','validando','na_fila','extraindo',
                                    'classificando','aguardando_ia','pendente_revisao',
                                    'parcialmente_revisado','concluido','erro_formato',
                                    'erro_extracao','erro_classificacao','erro_timeout',
                                    'cancelado','reprocessando'
                                )),
    total_lancamentos       INTEGER       NOT NULL,
    usuario_id              BIGINT        NOT NULL,
    versao                  INTEGER       NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE gastos (
    id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    categoria VARCHAR(255)  NOT NULL
                  CHECK (categoria IN ('ALIMENTACAO','TRANSPORTE','LAZER','MORADIA')),
    data      DATE          NOT NULL,
    descricao VARCHAR(255)  NOT NULL,
    usuario_id BIGINT       NOT NULL,
    valor     NUMERIC(38,2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE motivos_cancelamento (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    ativo                    BOOLEAN      NOT NULL,
    motivos_cancelamento_code VARCHAR(6)  NOT NULL,
    criado_em                TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    descricao                VARCHAR(255) NOT NULL,
    origem_permitida         VARCHAR(20)  NOT NULL
                                 CHECK (origem_permitida IN (
                                     'usuario','sistema','admin','todos'
                                 )),
    PRIMARY KEY (id)
);

CREATE TABLE notificacoes (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    canal      VARCHAR(20)  NOT NULL
                   CHECK (canal IN ('whatsapp','telegram','email')),
    criado_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    enviada    BOOLEAN      NOT NULL,
    enviada_em TIMESTAMP(6) WITH TIME ZONE,
    erro       TEXT,
    mensagem   TEXT,
    tentativas SMALLINT     NOT NULL,
    tipo       VARCHAR(50)  NOT NULL,
    titulo     VARCHAR(255),
    usuario_id BIGINT       NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE parser_versoes (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    ativo           BOOLEAN      NOT NULL,
    banco           VARCHAR(100) NOT NULL,
    depreciado_em   TIMESTAMP(6) WITH TIME ZONE,
    descricao       TEXT,
    score_qualidade NUMERIC(4,3),
    total_erros     INTEGER      NOT NULL,
    total_usos      INTEGER      NOT NULL,
    versao          VARCHAR(20)  NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE processamento_jobs (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    concluido_em    TIMESTAMP(6) WITH TIME ZONE,
    correlation_id  BIGINT,
    enfileirado_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    erro_mensagem   TEXT,
    extrato_id      BIGINT,
    iniciado_em     TIMESTAMP(6) WITH TIME ZONE,
    lock_expires_at TIMESTAMP(6) WITH TIME ZONE,
    max_tentativas  SMALLINT     NOT NULL,
    payload         TEXT,
    proximo_retry   TIMESTAMP(6) WITH TIME ZONE,
    status          VARCHAR(30)  NOT NULL
                        CHECK (status IN (
                            'enfileirado','iniciando','processando','aguardando_ia',
                            'concluido','falha_ia','falha_parser','timeout',
                            'retry_1','retry_2','retry_3','dead_letter','cancelado'
                        )),
    tentativas      SMALLINT     NOT NULL,
    tipo            VARCHAR(30)  NOT NULL
                        CHECK (tipo IN (
                            'extracao_pdf','classificacao_ia','notificacao',
                            'geracao_pdf','snapshot','anonimizacao'
                        )),
    worker_id       VARCHAR(100),
    PRIMARY KEY (id)
);

CREATE TABLE snapshots_financeiros (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    ano            SMALLINT      NOT NULL,
    conta_id       BIGINT,
    fechado        BOOLEAN       NOT NULL,
    fechado_em     TIMESTAMP(6)  WITH TIME ZONE,
    mes            SMALLINT      NOT NULL,
    saldo_final    NUMERIC(15,2) NOT NULL,
    saldo_inicial  NUMERIC(15,2) NOT NULL,
    total_gastos   NUMERIC(15,2) NOT NULL,
    total_receitas NUMERIC(15,2) NOT NULL,
    usuario_id     BIGINT        NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE transacoes (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    atualizado_em        TIMESTAMP(6)  WITH TIME ZONE,
    categoria_id         BIGINT,
    transacoes_code      VARCHAR(6)    NOT NULL,
    confianca_ia         SMALLINT,
    conta_id             BIGINT        NOT NULL,
    criado_em            TIMESTAMP(6)  WITH TIME ZONE NOT NULL,
    data_lancamento      TIMESTAMP(6)  WITH TIME ZONE NOT NULL,
    data_transacao       DATE          NOT NULL,
    deleted_at           TIMESTAMP(6)  WITH TIME ZONE,
    descricao_normalizada VARCHAR(255),
    descricao_original   TEXT,
    descricao_usuario    VARCHAR(255),
    estabelecimento      VARCHAR(255),
    extrato_id           BIGINT,
    observacao           TEXT,
    origem               VARCHAR(20)   NOT NULL
                             CHECK (origem IN ('manual','pdf','api')),
    periodo_recorrencia  VARCHAR(20),
    recorrente           BOOLEAN,
    status_revisao       VARCHAR(30)   NOT NULL
                             CHECK (status_revisao IN (
                                 'extraida','classificada','pendente_revisao',
                                 'confirmada','ignorada','arquivada'
                             )),
    subcategoria         VARCHAR(100),
    tipo                 VARCHAR(10)   NOT NULL
                             CHECK (tipo IN ('RECEITA','GASTO')),
    transacao_estorno_id BIGINT,
    valor                NUMERIC(15,2) NOT NULL,
    versao               INTEGER       NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE transacoes_canceladas (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    cancelado_em   TIMESTAMP(6)  WITH TIME ZONE NOT NULL,
    cancelado_por  VARCHAR(20)   NOT NULL
                       CHECK (cancelado_por IN ('usuario','sistema','admin')),
    conta_id       BIGINT        NOT NULL,
    ip_origem      VARCHAR(45),
    motivo_id      BIGINT        NOT NULL,
    observacao     TEXT,
    transacao_id   BIGINT        NOT NULL,
    usuario_id     BIGINT        NOT NULL,
    valor_original NUMERIC(15,2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE usuarios (
    id_usuario      BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    cpf             VARCHAR(255) NOT NULL,
    dt_nascimento   DATE         NOT NULL,
    email           VARCHAR(255) NOT NULL,
    email_verificado BOOLEAN,
    nome            VARCHAR(255) NOT NULL,
    senha           VARCHAR(255) NOT NULL,
    telefone        VARCHAR(255),
    telegram_chatid BIGINT,
    usuario_code    VARCHAR(255) NOT NULL,
    whatsapp_chatid BIGINT,
    PRIMARY KEY (id_usuario)
);


-- ═══════════════════════════════════════════════════════════════
--  CONSTRAINTS UNIQUE  (extraídas dos ALTER TABLE do Hibernate)
-- ═══════════════════════════════════════════════════════════════

-- categoria_thresholds: um threshold por categoria
ALTER TABLE categoria_thresholds
    ADD CONSTRAINT UKhof89v3ea15cfy69fhfvgv6op UNIQUE (categoria_id);

-- categorias: code único
ALTER TABLE categorias
    ADD CONSTRAINT UKk73kpeiqdy6n11qojlj39hose UNIQUE (categorias_code);

-- contas_financeiras: code único
ALTER TABLE contas_financeiras
    ADD CONSTRAINT UKq6yk4e2ao66xqitn12j3hbt19 UNIQUE (contas_code);

-- extratos: code único
ALTER TABLE extratos
    ADD CONSTRAINT UKayk58p7exmctcn9m14kdh1xp1 UNIQUE (extratos_code);

-- motivos_cancelamento: code único
ALTER TABLE motivos_cancelamento
    ADD CONSTRAINT UK77wlysvh4n8d5hhe8we8v0kv1 UNIQUE (motivos_cancelamento_code);

-- transacoes: code único
ALTER TABLE transacoes
    ADD CONSTRAINT UK67f5gtn438e7ykddm9ydssp99 UNIQUE (transacoes_code);

-- usuarios: cpf, email e usuario_code únicos
ALTER TABLE usuarios
    ADD CONSTRAINT UK2et2smpfrtsohr7w9fe1v8a5e  UNIQUE (cpf);

ALTER TABLE usuarios
    ADD CONSTRAINT UKkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);

ALTER TABLE usuarios
    ADD CONSTRAINT UKh8plsiwilrerynftorecsi633  UNIQUE (usuario_code);